Ensembl/public-plugins

widgets/htdocs/widgets/95_SpeciesTree.js
widgets/modules/EnsEMBL/Web/Document/HTML/Compara/SpeciesTree.pm

Summary of changes:
- there can be more than 2 trees. The Perl code will fetch all the trees that the compara db is exposing
- species filters and the default tree are defined in the compara db

Get the species trees from the compara db

---

tools/modules/EnsEMBL/Web/Component/Tools/VEP/InputForm.pm

Previously if examples are not present there was a runtime error: hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at /nfs/public/rw/ensembl/libs/perl/share/perl5/JSON.pm line 154

Don't die if examples are not available

---

tools_hive/modules/EnsEMBL/Web/RunnableDB/IDMapper.pm

The bug in this script is resulting in the buildup of the following command:
perl ...........metazoa/ensembl-tools/scripts/id_history_converter/IDmapper.pl --port 4160  --pass  --user ensro --host mysql-eg-staging-1.ebi.ac.uk --species Aedes_aegypti ......
Thus 'pass' key is being assigned value '--user'.

EG doesnt use password for anything except userdata dbs. Causing issue at this stage when only host, user and port are passed to this script.

---

docs/htdocs/info/docs/tools/vep/script/vep_cache.html
docs/htdocs/info/docs/tools/vep/script/vep_download.html

Changes have been made to the VEP to use Faidx (FASTA indexing from HTSlib) from Bio::DB::HTS rather than its own module, as detailed in the merged pull request at https://github.com/Ensembl/ensembl-tools/pull/12. These documentation changes accompany this.

update to VEP docs reflecting move to Bio::DB::HTS module from faidx_xs

---

docs/htdocs/info/docs/api/api_installation.html

BioPerl website has been re-organized, fetch the GZ archive from CPAN instead.

BioPerl GZ archive updated

---

tools/htdocs/components/35_blast_form.css

The BLAST sequence box renders in a non-fixed width font on some distros of Linux as the font 'Courier' is not installed.  Have added in a 'monospace' fallback for these users.

Add a fallback fixed width font for BLAST sequence box

---

ensembl/htdocs/info/data/mysql.html

As suggested by Wojciech Bazant we have clarified the MySQL client you can use to query Ensembl databases. We also expanded the list of clients available

Cleaning up MySQL client list

---

docs/htdocs/info/website/adding_trackhubs.html

Highlighted by Ann Zweig we were pointing to the wrong docs.

Point to the right URL for track hub docs

---

docs/htdocs/info/docs/api/variation/variation_tutorial.html

Changes to replace deprecated methods that will be removed in release 88.
Change examples to variants that return results
@ens-lgil Please can you review.

Modifications to Variation API tutorial

---

widgets/modules/EnsEMBL/Web/Document/HTML/Compara/SpeciesTree.pm

Tested on my sandbox: http://enssand-02.internal.sanger.ac.uk:9073/info/about/speciestree.html
Divergence times are still completely missing, clade names are partially missing. Both can be restored by either applying a .sql patch or hardcoding the values in the Compara API

Changes to use more generic Compara methods that are now available directly on the SpeciesTreeNode object

---

tools_hive/modules/EnsEMBL/Web/RunnableDB/IDMapper.pm

Enabling Ensembl Genomes to use its own db server instead of Ensembl's public db server for IDMapper

ENSEMBL-5010 & ENSEMBL-4946 - Enabling others to use their own db server instead of Ensembl's public db server for IDMapper

---

docs/htdocs/info/about/legal/code_licence.html

**Please wait before accepting in**
Switching back to the original apache license text but also added a new section for Ensembl.

Switching to original apache 2 license text

---

docs/htdocs/info/website/public_trackhubs.html

the beta url does not exist any more, updated the documentation to link to the public URL

beta url retired for trackhub registry

---

docs/htdocs/info/docs/api/core/core_tutorial.html

- clone RP11-62N12 does not exist in current human core db, replaced it with RP5-60P11
- current human db does not contain supercontigs 'NT_011333' : replaced example to scaffold 'KI270510.1'
- current human get ProteinAlignFeatures('Swall') is empty, replaced the type with 'Uniprot'

core_tutorial corrected typos and updated to working example

---

docs/htdocs/info/docs/api/core/core_tutorial.html

Removed outdated/not supported 'Other Scripts' section to avoid potential misguidance, see github issue: https://github.com/pycogent/pycogent/issues/78

remove old link and scripts references

---

ensembl/conf/json/capra_hircus_vcf.json
ensembl/conf/json/ovis_aries_vcf.json

Updated config files with new genotype data for goat and sheep. The data needs to be copied from the production area.

Update vcf configs

---

ensembl/conf/SiteDefs.pm
tools/htdocs/components/20_BlastForm.js

This pull request is for ENSWEB-4464. 'U' has been added to check DNA sequence type. The 'U' is replaced by 'T' to prevent BLAST jobs from failing. Flags are used to display a message about this to the user. The sandbox links is: http://ves-hx-78.ebi.ac.uk:8310/Multi/Tools/Blast.

RNA Sequence Support for BLAST

---

ensembl/htdocs/info/genome/compara/family.html
ensembl/htdocs/info/genome/compara/homology_method.html

in e94 we changed the method used to define the gene-trees. This pull request addresses that, and fixes a few layout issues too.
Emily has already proofread and corrected the changes.
Matthieu

Updated compara documentation for e94

---

docs/htdocs/info/docs/Doxygen/index.html
docs/htdocs/info/docs/eHive.html
docs/htdocs/info/docs/webcode/mirror/tools/index.html

Updated links to eHive documentation. Comprehensive guiHive documentation is not yet in the user manual, so leaving the pointer to README.md for it.

ENSWEB-4752: update links to eHive documentation

---

tools/modules/EnsEMBL/Web/Component/Tools/LD/Results.pm
tools_hive/modules/EnsEMBL/Web/RunnableDB/LD.pm

Emily reported an [error](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-1456) with the LD tool. The reason being that the code tries to read a file which doesn't exists. It looks like [this](http://www.ensembl.org/Homo_sapiens/Tools/LD/Results?db=core;tl=YVzY3V44mnTLydyO-4680948) on the main site. And is fixed with this PR and tested on my [sandbox](http://ves-hx2-76.ebi.ac.uk:5040/Homo_sapiens/Tools/LD/Results?db=core;tl=HesxpTd7ou9irJEF-249). Could you update the live site with the bug fix please? Do you want a PR for master and/or release/94 branch.
Thank you!

Ld tool bug fix 94

---

tools/modules/EnsEMBL/Web/Job/VEP.pm

@sanjay-boddu 
This is a PR which attempts to solve the problem with the 2 tickets running out of memory.
The PR will reduce the buffer size only if VEP is run with regulation option. You can see that on my [sandbox](http://ves-hx2-76.ebi.ac.uk:5040/Homo_sapiens/Tools/VEP/Results?db=core;tl=Ep0MmLprbfgsNNTe-269) it is added to the command line. (I wonder if Get regulatory region consequences: should be default to NO, @sarahhunt ?).

reduce buffer_size if run with regulatory option

---

ensembl/htdocs/info/genome/variation/species/index.html
ensembl/htdocs/info/genome/variation/species/sources_documentation.html
ensembl/htdocs/info/genome/variation/species/species_data_types.html

Also moved broad data descriptions up a level and the information on viewing tracks from spectifi data sources to the sources page.

updates to describe species supported direct from EVA

---

ensembl/conf/json/chlorocebus_sabaeus_vcf.json

We are adding variation data for vervet by reading most of the data from VCF. This makes use of the VCF backend code which has been added by Will.

configure VCF file for vervet

---

ensembl/conf/json/homo_sapiens_vcf.json

Update json config to read GERP and CADD scores from file and display on variant summary page.

add source for CADD and GERP score

---

tools/htdocs/components/20_VEPForm.js
tools/modules/EnsEMBL/Web/VEPConstants.pm

Additional format for VEP in e96: `SPDI`
This PR gives the possibility to use the SPDI format as input on the Web VEP form.
http://ves-hx2-76.ebi.ac.uk:5060/Homo_sapiens/Tools/VEP/Results?db=core;g=ENSG00000135744;r=1:230702523-230714122;t=ENST00000366667;tl=CMABGKZrMOr075fk-607

Add the SDPI format to the list of the Web VEP input format

---

widgets/htdocs/components/95_PDB.js

Fixing a missing Core data change I couldn't test before the Test REST server was available.
See an example with the fix on my sandbox:
http://ves-hx2-76.ebi.ac.uk:5060/Homo_sapiens/Variation/PDB?v=rs699

Update PDBe JS regarding some data changes in Ensembl REST

---

tools_hive/conf/vep_plugins_hive_config.txt

Added missing parameter for CADD files for e96 GRCh38 web.
Example of sandbox with results showing for CADD, columns CADD PHRED, CADD RAW:
http://ves-hx2-76.ebi.ac.uk:6080/Homo_sapiens/Tools/VEP/Results?db=core;tl=SboxrAwK3AT2CPEt-655

fix add cadd files parameter grch38

---

tools/modules/EnsEMBL/Web/Component/Tools/VEP/Results.pm

This is a way to reduce the size of the VEP results table, by hidding the less popular columns (which are returned by default by VEP).

Hide some of the VEP columns by default

---

docs/htdocs/info/docs/tools/simulator/index.html
ensembl/htdocs/info/genome/variation/tools/variant_tools.html

Add documentation for variant simulator tool:
- https://www.ensembl.org/info/genome/variation/tools/variant_tools.html
- update: http://ves-hx2-76.ebi.ac.uk:6080/info/genome/variation/tools/variant_tools.html
update: http://ves-hx2-76.ebi.ac.uk:6080/info/docs/tools/simulator/index.html

add variant simulator doc page -e97

---

tools/modules/EnsEMBL/Web/Component/Tools/VEP/InputForm.pm
tools/modules/EnsEMBL/Web/Job/VEP.pm
tools/modules/EnsEMBL/Web/Object/VEP.pm
tools/modules/EnsEMBL/Web/VEPConstants.pm

This change allows the user to change the buffer_size used in web VEP.
There were several cases where the VEP job failed because of memory issue. This option will prevent the webteam to manually to change the input buffer on the server: we could point the users to this new form and ask them to choose a lower value for the buffer of their jobs.
Here is an example on my sandbox (**Advanced options**):
http://ves-hx2-76.ebi.ac.uk:5060/Homo_sapiens/Tools/VEP?db=core

Add a new option in the VEP input form to change the buffer_size

---

tools/modules/EnsEMBL/Web/Component/Tools/VEP/InputForm.pm
tools/modules/EnsEMBL/Web/Component/Tools/VEP/Results.pm
tools/modules/EnsEMBL/Web/Job/VEP.pm
tools/modules/EnsEMBL/Web/Object/VEP.pm

WEB VEP input form:
- transcript_version will be used by default unless box is unchecked
Web VEP result: 
- checked: http://ves-hx2-76.ebi.ac.uk:6080/Sus_scrofa/Tools/VEP/Results?db=core;tl=uVMWPfYnPFIU0gWY-720
- unchecked :  http://ves-hx2-76.ebi.ac.uk:6080/Sus_scrofa/Tools/VEP/Results?db=core;tl=DNRX0JO287CnsSp9-722

add checkbox for transcript_version option

---

ga/htdocs/components/95_ga_configs.js

**NOTE:** This needs to released along with the following PR:
https://github.com/Ensembl/ensembl-webcode/pull/719
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5228
Extended the analytics tracking to the variation tables on the following pages:
- Gene
- Transcripts
- Protein
All the clicks to the links inside the table along with the filters are now tracked.
- Gene - http://ves-hx2-76.ebi.ac.uk:42229/Danio_rerio/Gene/Variation_Gene/Table?db=core;g=ENSDARG00000024771;r=18:5213338-5227420;t=ENSDART00000033574;v=rs506965281;vdb=variation;vf=14193096
- Transcript - http://ves-hx2-76.ebi.ac.uk:42229/Danio_rerio/Transcript/Variation_Transcript/Table?db=core;g=ENSDARG00000024771;r=18:5213338-5227420;t=ENSDART00000033574;v=rs506965281;vdb=variation;vf=14193096
- Protein - …

Extend tracking to variation tables

---

ensembl/conf/ini-files/sus_scrofa.ini
ensembl/conf/ini-files/sus_scrofa_bamei.ini
ensembl/conf/ini-files/sus_scrofa_berkshire.ini
ensembl/conf/ini-files/sus_scrofa_hampshire.ini
ensembl/conf/ini-files/sus_scrofa_jinhua.ini
ensembl/conf/ini-files/sus_scrofa_landrace.ini
ensembl/conf/ini-files/sus_scrofa_largewhite.ini
ensembl/conf/ini-files/sus_scrofa_meishan.ini
ensembl/conf/ini-files/sus_scrofa_pietrain.ini
ensembl/conf/ini-files/sus_scrofa_rongchang.ini
ensembl/conf/ini-files/sus_scrofa_tibetan.ini
ensembl/conf/ini-files/sus_scrofa_usmarc.ini
ensembl/conf/ini-files/sus_scrofa_wuzhishan.ini

Fixed the issue with missing 'Strains' link on the nav bar for Pigs.
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5275
Views affected:
http://ves-hx2-76.ebi.ac.uk:42228/Sus_scrofa/Gene/Summary?g=ENSSSCG00000004244;r=1:42729112-42896283

Pig-strains gene-trees not shown on staging #5275 

---

solr/conf/SiteDefs.pm

Strains that can be shown in the left-hand sidebar of the search page are white-listed in SiteDefs of the Solr plugin. This PR updates the SideDefs so that pig strains are also searchable.
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5295
([view in sandbox](http://ves-hx2-76.ebi.ac.uk:8410/Sus_scrofa/Search/Results?q=ENSSSCG00055009074;page=1;facet_species=Pig))

Update Solr SiteDefs to account for pig strains in sidebar

---

ensembl/conf/ini-files/homo_sapiens.ini

We didn't correctly set which variants belong to the set "1000 Genomes 3 - All" which means that the default track variation_set_1kg_3 would be empty. We switched the default track to variation_set_gnomAD instead.

replace variation_set_1kg_3 with gnomad

---

ensembl/conf/ini-files/sus_scrofa.ini
ensembl/conf/ini-files/sus_scrofa_bamei.ini
ensembl/conf/ini-files/sus_scrofa_berkshire.ini
ensembl/conf/ini-files/sus_scrofa_hampshire.ini
ensembl/conf/ini-files/sus_scrofa_jinhua.ini
ensembl/conf/ini-files/sus_scrofa_landrace.ini
ensembl/conf/ini-files/sus_scrofa_largewhite.ini
ensembl/conf/ini-files/sus_scrofa_meishan.ini
ensembl/conf/ini-files/sus_scrofa_pietrain.ini
ensembl/conf/ini-files/sus_scrofa_rongchang.ini
ensembl/conf/ini-files/sus_scrofa_tibetan.ini
ensembl/conf/ini-files/sus_scrofa_usmarc.ini
ensembl/conf/ini-files/sus_scrofa_wuzhishan.ini

This PR is to update the wrong `RELATED_TAXON` used in the following PR:
https://github.com/Ensembl/public-plugins/pull/252
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5275
Views affected:
http://ves-hx2-76.ebi.ac.uk:42228/Sus_scrofa/Gene/Strain_Compara?g=ENSSSCG00000004484;r=1:90744429-90875118

Update pig related taxon

---

widgets/conf/SiteDefs.pm

This should fix the PDBe viewer issue when using Ensembl with the HTTP protocol.

Replace the PDBe URLs by using HTTPS by default

---

ensembl/conf/json/salmo_salar_vcf.json

Read variants for Atlantic salmon from VCF file hosted by EVA.

new variation species from VCF only

---

tools/modules/EnsEMBL/Web/Object/Blast.pm

**Problem**
We noticed that running BLAST for species whose "regions" (genetic molecules of a similar class as chromosomes — scaffolds, assemblies, etc.) are versioned produces missing results. For example:
- search for NM_001142896.1 in Ensembl global search; it will result in a number of matches for pig breeds
- click on a match, select `cDNA` in the left-hand sidebar, and click on "Blast this sequence"
- run blast (making sure that you are running it for genomic sequence), and view the results
- click on any result; notice that the `r` parameter in the url begins with a versioned region (the part before the colon); also notice in the bottom image (which should contain the blasted sequence) tracks that say that the sequence was not found
The example above was reported in ENSWEB-5322 and …

Update Blast.pm logic to account for versioned regions

---

tools/modules/EnsEMBL/Web/Object/Blast.pm

PR https://github.com/Ensembl/public-plugins/pull/275 introduced a faulty bit of code that Perl is complaining about. It doesn't like to compare `undef` to a string and is spamming our logs with warning messages about its unhappiness.

Add empty string to avoid warning when comparing a string to undef

---

tools/htdocs/components/31_forms.css

Bottom fieldset in the BLAST and VEP tools form overlaps with the previous field:
`.extra-options-fieldset` has a negative margin of `-40px`, which is too much and pulls the bottom fieldset over the previous field.
Change the negative margin to a smaller one?
**Sandbox:** http://ves-hx2-76.ebi.ac.uk:8410/Multi/Tools/Blast?db=core for BLAST and http://ves-hx2-76.ebi.ac.uk:8410/Multi/Tools/VEP?db=core for VEP
The markup of the whole Tools form is currently very... unorthodox and fragile, and I couldn't find the actual change that was responsible for the broken interface. But it will take too much time to refactor this form to a more predictable markup. I am sure it isn't worth the time and effort.

Change margin-top for extra-options-fieldset

---

ensembl/htdocs/info/genome/compara/species_trees.html
widgets/htdocs/info/about/speciestree.html

This has been reported by a user in `ensembl-dev` mail list.

Bugfix: point species tree link to the actual file instead of symlink

---

ensembl/htdocs/info/about/speciestree.html
ensembl/htdocs/info/genome/compara/species_trees.html
widgets/htdocs/info/about/speciestree.html

The default location of the species trees has changed in `ensembl-compara` from e99 on. This PR updates the location (and filename) of the vertebrates species tree file.

Changed path of vertebrates species tree

---

ga/htdocs/components/95_ga_configs.js

Added tracking to the `Run` and `Run Instant VEP` buttons on the VEP tool page.
Sandbox URL:
http://ves-hx2-76.ebi.ac.uk:42228/Homo_sapiens/Tools/VEP?db=core

Add tracking to VEP tool run buttons

---

ensembl/htdocs/info/genome/genebuild/haplotypes_patches.html

This PR fixes link for an embedded youtube video (as [explained on StackOverflow](https://stackoverflow.com/a/25661346/3925302), links to youtube videos in iframes embedded in external sites should have pathname that contains the word `embed` instead of `watch`).
Before fix:
After fix:
Link to page in a sandbox:
http://ves-hx2-76.ebi.ac.uk:8410/info/genome/genebuild/haplotypes_patches.html

Fix link for embedded youtube video

---

tools/htdocs/components/20_ThousandGenome.js

Ticket ENSWEB-4799 (see @ens-st3 's comment)
When data slicer cannot retrieve url to data file on ftp from 1000 genomes, it shows an error message that reads: "Genotype file URL: We were unable to retrieve the file, please try again later.(No file obtained)". This PR:
- replaces this message with a friendlier and more human-readable message
- the message has a link to the contact form for helpdesk
- contact form's subject field is pre-populated with a meaningful title: "Data slicer unable to retrieve genotype file from 1000G FTP site"
**Sandbox for testing:**
http://ves-hx2-76.ebi.ac.uk:8410/Homo_sapiens/Tools/DataSlicer
In order to see the new error message in the sandbox, you can simply block the request to the `_search` endpoint in Chrome Dev Tools (open dev tools, click on More tools, …

Update error message when data slicer cannot get url to file with data

---

docs/htdocs/info/docs/tools/vep/vep_formats.html

Update the example input for representing structural variants with the VEP tab-delimited default file format.

add identifiers to VEP default input for sv

---

tools/conf/SiteDefs.pm
tools/htdocs/components/20_ThousandGenome.js
tools/modules/EnsEMBL/Web/Component/Tools/DataSlicer/InputForm.pm
tools/modules/EnsEMBL/Web/Component/Tools/ThousandGenomeInputForm.pm

Update ftp host name for 1000 ftp server.
Also, hack our way on the client where we talk with the search server at https://www.internationalgenome.org. The server has to receive ftp url as a parameter, returns empty response if we change the ftp url to the new one, and  is not going to be reconfigured to correctly handle the new one 😞 
**Jira:** ENSWEB-5524
**Sandbox:** http://ves-hx2-76.ebi.ac.uk:8410/info/docs/tools/index.html
~Related PR in ebi-plugins: https://github.com/Ensembl/ebi-plugins/pull/36~

Update urls for 1000 genomes ftp site

---

solr/htdocs/solr/02_solr_search.js
solr/src/search.coffee

Description:
Quick and dirty fix for the Zebra finch search issue for e99.
Sandbox URL:
http://ves-hx2-76.ebi.ac.uk:42229/Taeniopygia_guttata/Info/Index
Related ticket:
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5610

Zebra finch search fix for 99

---

ensembl/conf/ini-files/DEFAULTS.ini

Changing the protocol for accessing files on ftp.ensembl.org from `ftp://` to `http://`, because:
- there is a firewall on web machines, which the FTP client was not using (potentially solvable by adding the [firewall option](https://perldoc.perl.org/Net/FTP.html) to the FTP client (see _ftp_file_exists method on [BaseAnnotationAdaptor](https://github.com/Ensembl/ensembl-variation/blob/release/99/modules/Bio/EnsEMBL/Variation/DBSQL/BaseAnnotationAdaptor.pm))
- in general, http protocol should be preferred over ftp as more resilient
Sandbox:
http://ves-hx2-76.ebi.ac.uk:8410/Homo_sapiens/Variation/Explore?r=1:230709548-230710548;v=rs699;vdb=variation;vf=179
notice the presence of the GERP score in the "Change tolerance" line
**Note:** the sandbox also contains changes in …

Use http instead of ftp protocol to access files form ftp server

---

ensembl/conf/json/homo_sapiens_vcf.json

Display new gnomad v3 data on [variant page](http://ves-hx2-76.ebi.ac.uk:5040/Homo_sapiens/Variation/Population?db=core;r=1:230845294-230846294;v=rs699;vdb=variation;vf=179#gnomadgenomes_anchor).

add gnomad v3 grch38 vcf location

---

ensembl/htdocs/info/genome/compara/homology_method.html

Compara is removing dN/dS data from their database, and we are removing dN/dS from the site.
Related PR in ensembl-webcode: https://github.com/Ensembl/ensembl-webcode/pull/767
Jira ticket: ENSWEB-5457
Sandbox: http://ves-hx2-76.ebi.ac.uk:8410/info/genome/compara/homology_method.html

Remove dN/dS from Compara docs (homology_method.html)

---

solr/htdocs/components/65_autocomplete.js

**Related JIRA:**
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5504
**Description**
Fixed the issue with the autocomplete where the ontology accession direct links are broken. 
**Sandbox URL:**
http://ves-hx2-76.ebi.ac.uk:42229/Homo_sapiens/Info/Index?db=core

Fix search autocomplete ontology directlinks

---

ensembl/conf/ini-files/saccharomyces_cerevisiae.ini

The bug was initially reported by Ameya and is described in the JIRA ticket:
https://www.ebi.ac.uk/panda/jira/browse/ENSINT-491
There has been a change in the syntax on how SGD is accessed
Instead of 
http://db.yeastgenome.org/cgi-bin/locus.pl?locus=###ID###
It needs to be
https://www.yeastgenome.org/locus/###ID###
There are at least two files where this information is stored:
https://github.com/Ensembl/public-plugins/blob/release/100/ensembl/conf/ini-files/saccharomyces_cerevisiae.ini#L70
and
https://github.com/EnsemblGenomes/eg-web-common/blob/release/eg/47/conf/ini-files/DEFAULTS.ini
Are there any others?

Fix sgd url

---

covid19/modules/EnsEMBL/Web/Component/Info.pm

This PR is to fix the broken FTP site URLs in the COVID-19 site species homepage.
Related JIRA:
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5872
Sandbox URL:
http://ves-hx2-76.ebi.ac.uk:42227/Sars_cov_2/Info/Index

COVID-19 - Fix FTP site URLs in the species homepage

---

ensembl/conf/SiteDefs.pm

This PR fixes the issue with missing species image for Cat on the assembly and annotation page.
https://www.ensembl.org/Felis_catus/Info/Annotation
Related JIRA:
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5864
Sandbox URL:
http://ves-hx2-76.ebi.ac.uk:42229/Felis_catus/Info/Annotation

Add missing SPECIES_IMAGE_DIR

---

ensembl/htdocs/info/genome/variation/phenotype/phenotype_annotation.html
ensembl/htdocs/info/genome/variation/tools/data_access.html
ensembl/htdocs/info/genome/variation/tools/variant_tools.html

New section "Phenotype classes":
http://ves-hx2-76.ebi.ac.uk:6080/info/genome/variation/phenotype/phenotype_annotation.html
vs
https://www.ensembl.org/info/genome/variation/phenotype/phenotype_annotation.html
Also update http to https for REST in :
http://ves-hx2-76.ebi.ac.uk:6080/info/genome/variation/tools/data_access.html
http://ves-hx2-76.ebi.ac.uk:6080/info/genome/variation/tools/variant_tools.html

Add phenotype class docs

---

ensembl/conf/json/homo_sapiens_vcf.json

We are planning to display frequencies from the Gambian Variation Project. The data is remotely stored under http://ftp.1000genomes.ebi.ac.uk/
I tested the configuration on my sandbox. However, I cannot get tabix to retrieve data from remote VCF files on my sandbox and had to copy one VCF file to my sandbox for testing.
I can retrieve the data on the farm with a script I have written.

add configuration for GGVP data

---

ensembl/conf/json/ovis_aries_rambouillet_vcf.json

ovis_aries_rambouillet is the new reference and we have a variation database for this species from release 102. This PR is needed to configure the location of the GERP file. GERP scores are shown on the variation summary page.

show gerp scores for new sheep reference

---

docs/htdocs/info/docs/tools/vep/script/vep_other.html

The url to download bam files has changed and is now creating a 404 error. I changed the url with a stable release version now.

update bam file loction to stable release

---

tools/modules/EnsEMBL/Web/Job/VEP.pm

**Description:**
This PR is to fix the intermittent error that was breaking the VEP tool jobs.
The problem is something to do with the following line:
https://github.com/Ensembl/public-plugins/blob/release/100/tools/modules/EnsEMBL/Web/Job/VEP.pm#L155
Modifying the value of $param somehow gets temporarily changed in the stored config.
To fix this, I'm just cloning the $param defined in the foreach to $param_clone and using it instead.
**Example ticket that was throwing this error:**
http://debug.ensembl.org/Homo_sapiens/Tools/VEP/View?db=core;tl=9QezRSx98mS7heaW-6524731
**Related JIRA:**
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5658

Fix VEP column not found bug

---

docs/htdocs/info/docs/tools/vep/vep_formats.html

There are some links from other parts of the documentation that link to hidden sections on vep_formats.html (e.g. info/docs/tools/vep/script/vep_other.html#refseq_match). 
Unhiding the section removes this issue, and makes it easier for users to find the documentation required.

Remove hiding of alternate vep output fields

---

ensembl/conf/json/homo_sapiens_vcf.json

Because of problems with igsr FTP site it was decided to move files to the ensembl ftp site and sync with internal file system (base path = /.../ensweb-data/data_files/www). The VCF files need to be copied to the internal file system before this PR is merged.
The files have already been copied to ../ensemblftp/data_files/homo_sapiens/GRCh38/variation_genotype/ggvp

move ggvp data to ensembl file system

---

widgets/modules/EnsEMBL/Web/Document/HTML/Compara/SpeciesTree.pm

https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5649
We need to tackle with duplicate names. I have tested features in the tree like download, circular tree etc. but there may be things I have missed due to this change. 
Fix sandbox url http://ves-hx-78.ebi.ac.uk:9000/info/about/speciestree.html

[ENSWEB-5649] Continue if there are duplicate names

---

docs/htdocs/info/docs/webcode/mirror/install/ensembl-data.html
ensembl/conf/SiteDefs.pm
ensembl/conf/ini-files/DEFAULTS.ini

The GRCh37 site's help page 'Installing the Ensembl Data' shows the vertebrate (www) FTP URL. This PR fixes that by adding a SiteDefs variable.
This PR needs to be merged at the same time as [68 in ebi-plugins](https://github.com/Ensembl/ebi-plugins/pull/68) is merged.

ENSWEB-5921: Fix wrong example FTP URL

---

solr/htdocs/components/65_autocomplete.js

Description:
- This PR is to fix the broken direct links when the gene stable_id has underscores in it
Related JIRA:
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6071
Sandbox URL:
http://ves-hx2-75.ebi.ac.uk:42229/Mus_caroli/Info/Index
Steps to reproduce:
1) Go to http://www.ensembl.org/Mus_caroli/Info/Index
2) Search for `twnk` gene
3) Select the option that says `Twnk  MGP_CAROLIEiJ_....`

Fix direct links space encoding issue

---

ensembl/htdocs/info/genome/variation/tools/variant_tools.html

Variant recoder is also available as a web tool.
Sandbox: http://ves-hx2-76.ebi.ac.uk:7040/info/genome/variation/tools/variant_tools.html

Variant Recoder - update documentation 

---

tools/modules/EnsEMBL/Web/Component/Tools/VEP/Results.pm
tools_hive/conf/vep_plugins_hive_config.txt

DisGeNET has a different output structure, `DisGeNET_PMID`, `DisGeNET_SCORE` and `DisGeNET_disease` are no longer used. Instead, the header is just `DisGeNET`. 
Sandbox to test: http://ves-hx2-76.ebi.ac.uk:7040/Tools/VEP 
input variant: rs699

Update DisGeNET output (104)

---

ensembl/conf/json/homo_sapiens_vcf.json

We start using gnomAD's liftover files.

replace gnomad exome files for grch38

---

docs/htdocs/info/docs/tools/vep/recoder/index.html

The Variant Recoder example is not valid anymore `p.Met268Thr` and the current output is by allele. 
Sandbox: http://ves-hx2-76.ebi.ac.uk:7040/info/docs/tools/vep/recoder/index.html

Docs - update Variant Recoder output example

---

ensembl/conf/json/oreochromis_niloticus_vcf.json

-- the wrong display group name was used
-- after the fix all still displays as expected (see [sandbox](http://ves-hx2-76.ebi.ac.uk:5040/Oreochromis_niloticus/Variation/Population?db=core;r=LG19:18792028-18872052;v=LG19:18819865:A_G:PRJEB38548;vdb=variation;vf=LG19:18819865:A_G:PRJEB38548))

update display group name

---

ensembl/htdocs/info/genome/genebuild/transcript_quality_tags.html

This bugfix corrects a faulty link in the [transcript tags documentation page](https://www.ensembl.org/info/genome/genebuild/transcript_quality_tags.html).
- Sandbox URL: http://wp-np2-1d.ebi.ac.uk:1610/info/genome/genebuild/transcript_quality_tags.html
- JIRA ticket: https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6235

Bugfix: faulty URL in deocumentation

---

genoverse/htdocs/genoverse/ensembl/js/Panel.js

I've been playing with a new google closure compiler, when it complained of an error in the merged javascript:
```
/homes/ens_adm06/tmp/8410/server/minified/11f009db9960d736e3a9413cab8870af.js.tmp:9396:34: ERROR - [JSC_PARSE_ERROR] Parse error. invalid assignment target                                               
9396|               track.prop('order') = orderReverse; 
```
The error must be coming from [here](https://github.com/Ensembl/public-plugins/blob/release/104/genoverse/htdocs/genoverse/ensembl/js/Panel.js#L505), and the compiler is correct — it is not valid javascript. This looks like a bit of jQuery, where the correct syntax will be as in this PR.
I don't know anything about the genoverse plugin, so couldn't check where this code is expected to run. Does the change make sense …

Fix syntax in Panel.js file in genoverse public plugin

---

docs/htdocs/info/docs/api/core/core_schema.html

The file `core_schema.html` has been updated for Release 105. 
No SVG file changes found (verified by checking file histories: [sql/table.sql](https://github.com/Ensembl/ensembl/commits/release/105/sql/table.sql) and [sql/foreign_keys.sql](https://github.com/Ensembl/ensembl/commits/release/105/sql/foreign_keys.sql)).

Update core schema diagrams for Release 105

---

covid19/modules/EnsEMBL/Web/Document/HTML/FTPtable.pm

Updates/fixes the FTP downloads page for Covid site.
Sandox: http://wp-np2-1d.ebi.ac.uk:1670/info/data/ftp/index.html
JIRA ticket: https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6272

Fix FTP links in Covid site

---

genoverse/htdocs/genoverse/ensembl/js/Track/View/Gene.js

A simple solution to add spacing between the transcript features.
Only problem is that it adds some spacing above first line of feature like shown in the image below.
Related PR:
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6334
Sandbox URL:
http://wp-np2-1d.ebi.ac.uk:42229/Homo_sapiens/Location/View?db=core;g=ENSG00000139618;r=13:52315086-52400268;t=ENST00000544455

Add space below each expanded transcript feature in genoverse - V2

---

docs/htdocs/info/docs/tools/vep/script/vep_options.html

There ia a mismatch between `--everything` flags mentioned in the documentation and those set in [Config.pm][code]. As such,
1. `--mirna` was added to the documentation.
2. `--var_synonyms` was removed from the documentation.
3. The arguments were reordered based on [Config.pm][code].
The changes were tested via the sandbox and seem to be working as expected.
[code]: https://github.com/Ensembl/ensembl-vep/blob/5aa4f5c8bdcdeb4dc27ba114497601dacdc66e73/modules/Bio/EnsEMBL/VEP/Config.pm#L139-L166

Fix documentation of VEP --everything argument

---

docs/htdocs/info/docs/api/general_instructions.html

Fixes the following issues and inconsistencies in code samples from https://www.ensembl.org/info/docs/api/general_instructions.html:
- 2nd code snippet:
- `$eg_registry` should be named `$registry` as in other examples
- `use Bio::EnsEMBL::Registry;` line is duplicated
- 3rd snippet:
- `$registry` used but not defined
- 4th snippet:
- `$37_registry` should be named `$registry` as in other examples
- Last code snippet:
- `$first_chromosome` is not defined, correct variable is `$first_clone`
- `$chromosomw` is misspelled

Fix code samples in Perl API general instructions

---

tools/modules/EnsEMBL/Web/Component/Tools/VEP/PDB.pm

Since this is specific to this tool, I think a workaround is the best option for now. It defers handling of versioned stable IDs to the API, which is (I think) the right thing to do.
See ticket https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6409

Fix VEP PDB display

---

docs/htdocs/info/docs/api/core/core_tutorial.html

Hey, this PR fixes the newline character in three lines of the core tutorial.

Fix core tutorial's newlines

---

widgets/htdocs/alphafold/dataFetchers.js
widgets/htdocs/alphafold/index.js
widgets/htdocs/components/95_AFDB.js

When we are displaying link to alphafold model in the left-hand sidebar, we are only checking:
- that this species has some alphafold analyses
- that the transcript has a translation
We are not checking that a given transcript specifically has alphafold analysis. Which means that sometimes we show users the link that opens a page with no alphafold models available.
The error we are showing in such case is too non-specific and confusing for the user:
This PR makes the text of the error more specific for cases when the Alphafold model is missing.
Relevant Slack conversation:
https://genomes-ebi.slack.com/archives/C0JBUBFRD/p1648660444283599
Sandbox:
http://wp-np2-1e.ebi.ac.uk:8450/Glycine_max/Transcript/AFDB?db=core;g=GLYMA_12G066300;r=12:4875471-4878097;t=KRH24850

Notify user of missing alphafold model

---

ensembl/conf/ini-files/homo_sapiens.ini

We wish to show the 'gnomAD-SV (dbVar study nstd166) (structural variants)' track by default and not the '1000 Genomes 3 - All (structural variants)' track. The 1000 Genomes track will still be available on the configuration options.

switch default SV track from 1KG to gnomAD

---

genoverse/htdocs/genoverse/ensembl/js/Track/library/RegulatoryFeature.js
genoverse/modules/EnsEMBL/Web/Controller/Genoverse.pm

**NOTE**: To be merged along with https://github.com/Ensembl/ensembl-webcode/pull/882
**Description:**
- Genoverse does not seem to have the functionality to display subtracks. I have introduced a `row` key to the features data returned by `fetch_fg_regulatory_features` that tells which feature needs to go into which row. The `row` key is then used to position the features on different `y-axis` to make them appear as if they are subtracks.
- Turned off the bumping for regulation tracks
**Sandbox URL**:
http://wp-np2-1d.ebi.ac.uk:42228/Homo_sapiens/Location/View?r=8:26291508-26372680
**Related JIRA**:
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6596

Reg subtracks on Genoverse

---

genoverse/htdocs/genoverse/ensembl/css/ensembl.css
genoverse/htdocs/genoverse/ensembl/js/00_extensions.js

Added text to the `genoverse_switch` image icon. This was the only icon in `public-plugins`. All the other icons are in `ensembl-webcode` repo and [a separate PR](https://github.com/Ensembl/ensembl-webcode/pull/887) is created for it.
e107
http://wp-np2-1e.ebi.ac.uk:8320/Homo_sapiens/Location/View?db=core;g=ENSG00000139618;r=13:32315086-32400268
Configuration headers/toolbars in Region in detail and Gene pages
[ENSWEB-6553](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6553)

Add text to image header configuration icons

---

ensembl/conf/json/canis_lupus_familiaris_vcf.json
ensembl/conf/json/canis_lupus_familiarisboxer_vcf.json
ensembl/conf/json/gallus_gallus_vcf.json

We are adding new genotype data from EVA vcf -
https://www.ebi.ac.uk/eva/?eva-study=PRJEB44919
In this process we need to update the vcf file information in the json config file. The genotype data is tested on sandbox -
e.g. - http://wp-np2-11.ebi.ac.uk:7070/Gallus_gallus/Variation/Population?db=core;r=1:196051926-196053237;v=rs739477247;vdb=variation;vf=4893594)

Update json configuration for new genotype data

---

tools/modules/EnsEMBL/Web/Component/Tools/VEP/Results.pm
tools/modules/EnsEMBL/Web/Component/Tools/VR/Results.pm

The method was removed from Web::Component::Shared in [this commit](https://github.com/Ensembl/ensembl-webcode/commit/f9f7ddcbf8ac52ab51802a4e0f99951c93152c71) in ensembl-webcode, which broke tables in tools.

Add the display_items_list method that got lost from the inheritance chain

---

ensembl/conf/ini-files/microtus_ochrogaster.ini
ensembl/conf/json/microtus_ochrogaster_vcf.json

Add support for remote EVA variants from Prairie vole (_Microtus ochrogaster_).
Tested in my sandbox: http://wp-np2-11.ebi.ac.uk:6070/Microtus_ochrogaster/Info/Index

Prairie vole EVA variants support (108)

---

ensembl/modules/EnsEMBL/Web/Component/Gene/ComparaOrthologs.pm

Verts & NVs use the same data structure but with different content. I've moved the code that builds the data structure into ensembl-webcode, so all we need in public-plugins (and eg-web-common) is the basic config listing the clades we want to use as the basis for the species sets.
See equivalent PRs https://github.com/Ensembl/ensembl-webcode/pull/888 and https://github.com/EnsemblGenomes/eg-web-common/pull/97

Remove duplicate code

---

ensembl/htdocs/info/genome/funcgen/process/peak-calling.html

A documentation change to info/genome/funcgen/process/peak-calling.html to clarify the procedure we use for filtering peaks (using the ENCODE exclusion list).

Clarify exclusion list filtering

---

ensembl/conf/json/sander_lucioperca_vcf.json

Add support for remote EVA variants from Pike-perche (_Sander lucioperca_).
Tested in my sandbox: http://wp-np2-11.ebi.ac.uk:6070/Sander_lucioperca/Location/View?r=VTTG01000001.1:5000-6000;db=core

Add pike-perch EVA variants (108)

---

ensembl/conf/json/coturnix_japonica_vcf.json
ensembl/conf/json/parus_major_vcf.json

[ENSVAR-4962](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4962)
Added support for Great tit (Parus_major)
Sandbox: http://wp-np2-11.ebi.ac.uk:6070/Parus_major/Location/View?r=2:71746274-71844284
[ENSVAR-4963](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4963)
Added support for Japanese quail (Coturnix_japonica)
Sandbox: http://wp-np2-11.ebi.ac.uk:6070/Coturnix_japonica/Location/View?r=3:71823736-72447687

Add great-tit and japanese-quail EVA variants (108)

---

docs/htdocs/info/docs/api/core/core_schema.html

The species list has been updated for Release 108. PR done on behalf of Infrastructure Team, task A6 (https://www.ebi.ac.uk/seqdb/confluence/pages/viewpage.action?spaceKey=ENSCORE&title=Core+release+coordination#CoreReleaseCoordination-UpdateSchemaDiagrams-A6).

Update core schema for 108

---

tools/conf/vep_plugins_web_config.txt
tools_hive/conf/vep_plugins_hive_config.txt

Adding new VEP plugin - mutfunc
sandbox link - http://wp-np2-11.ebi.ac.uk:7070/Homo_sapiens/Tools/VEP/Results?from=6;size=5;tl=Yylb3Po1ohtqmdGj-96;to=10#Results

Add mutfunc plugin for web VEP

---

tools/modules/EnsEMBL/Web/Component/Tools/VEP/InputForm.pm

`Transcript annotation` plugin was not getting attached to it respective section. That is why `NMD` is not appearing in input form.

Add respective plugin to its section

---

tools/modules/EnsEMBL/Web/ConfigPacker.pm

https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6641
This PR adds assembly converter chain files config to Configpacker.
This way there is less hassle during the release - updating configs in this ticket https://www.ebi.ac.uk/panda/jira/browse/ENSWEBREL-892
This is where we use the newly added configs will be used https://github.com/Ensembl/public-plugins/blob/release/107/tools/modules/EnsEMBL/Web/Object/AssemblyConverter.pm#L100
We may also delete the script to dump these configs mentioned in the above ticket.
http://wp-np2-1e.ebi.ac.uk:9002/

Add assembly converter chain files to configpacker

---

docs/htdocs/info/docs/api/compara/compara_tutorial.html

Fixed a broken link reported by a user in the Compara API tutorial.

Fixed broken link in Compara API tutorial

---

widgets/htdocs/alphafold/controllers/molstarController.js

This PR is for showing the appropriate message ("There is no Alphafold model for this molecule" rather than "An error occurred while loading the 3D protein viewer") if the alphafold api can't provide any data for a given id that we are sending.
Sandbox example:
http://wp-np2-1e.ebi.ac.uk:8410//Homo_sapiens/Transcript/AFDB?db=core;g=ENSG00000139618;r=13:32315086-32400268;t=ENST00000380152
_(As a sidenote, the reason this is even happening is because our rest api reports Alphafold analyses for large proteins that have been split into "fragments" (see [example query to our rest server](https://rest.ensembl.org/overlap/translation/ENSP00000369497?feature=protein_feature;type=alphafold))), whereas Alphafold is currently hiding them and …

Show appropriate error text when Alphafold api doesn't have a model file

---

docs/htdocs/info/docs/api/compara/compara_tutorial.html

The Compara Member method `fetch_by_stable_id` was deprecated in Ensembl release 107  and will be replaced by `fetch_by_stable_id_GenomeDB` in release 109. This update replaces all instances of the deprecated method in the Compara API tutorial.

Replace fetch_by_stable_id in Compara tutorial

---

docs/htdocs/info/docs/tools/vep/online/input.html
widgets/htdocs/alphafold/components/proteinFeaturesControlPanel.js
widgets/htdocs/alphafold/controllers/molstarController.js
widgets/htdocs/components/95_PDB.js

This PR updates retired Pfam URLs to the new site (InterPro).
Other affected repos listed in the JIRA ticket.
JIRA ticket: https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6701
Sandbox: http://wp-np2-1d.ebi.ac.uk:1680

Update Pfam URLs

---

docs/htdocs/info/docs/tools/vep/online/input.html
tools/conf/vep_plugins_web_config.txt

This PR is meant to add refactored plugin UTRAnnotator to web.
1) Use [sandbox](http://wp-np2-11.ebi.ac.uk:6070/Multi/Tools/VEP) with UTRAnnotator tagged in small VCF example:
VCF:
```sh
5       36876937        .       CC      A       .       .       .
8       22130707        .       A       G       .       .       .
1       112956192       .       C       T       .       .       .
11      31806913        .       TAA     T       .       .       .
4       153204530       .       G       GATGC   .       .       .
```
Also give a look at https://github.com/Ensembl/ebi-plugins/pull/137

feat: Add UTRAnnotator to web VEP

---

tools/modules/EnsEMBL/Web/Component/Tools/VEP/Results.pm

* [ENSVAR-4019](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4019):
* Strip protein version from UniProt links (otherwise, it directs users to a protein version page, instead of showing protein information).
* UniParc links were showing 404 error. Now the links correctly direct to UniProt.
* [ENSVAR-4020](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4020):
* Added links to UniProt Isoform entries.
* [ENSVAR-3396](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-3396):
* Added links to protein domains from CDD, Gene3D, PANTHER, Pfam, Prints, SMART, Superfamily, TIGRFAM, PIRSF, HAMAP and SFLD.
* For Gene3D protein domains, prefix the ID with G3DSA (otherwise, the URL returns an error).
* Requires code from [ensembl-webcode#926](https://github.com/Ensembl/ensembl-webcode/pull/926). …

Web VEP: fix UniProt URLs (e109)

---

tools/modules/EnsEMBL/Web/Component/Tools/VR/Results.pm

Add URL to all HGMD variants (release 109).
Sandbox: http://wp-np2-11.ebi.ac.uk:7040/Homo_sapiens/Tools/VR
Variant to test: rs138742754
HGMD in output is `BM1115006`

Variant Recoder fix HGMD url

---

tools/modules/EnsEMBL/Web/Component/Tools/VEP.pm
tools/modules/EnsEMBL/Web/Component/Tools/VEP/TicketDetails.pm

[ENSVAR-5208](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5208)
This PR adds a table containing VEP data versions in web VEP results (located in **Job Details** section). The information to create this table is retrieved from the line of VEP's VCF output that starts with `##VEP`, e.g.:
```
##VEP="v108" time="2022-10-24 16:50:52" cache="/net/isilonP/public/ro/ensweb-data/latest/tools/www/e108/vep/cache/homo_sapiens/108_GRCh38" db="homo_sapiens_core_108_38@hh-mysql-ens-species-web-1" 1000genomes="phase3" COSMIC="96" ClinVar="202205" HGMD-PUBLIC="20204" assembly="GRCh38.p13" dbSNP="154" gencode="GENCODE 42" genebuild="2014-07" gnomADe="r2.1.1" gnomADg="v3.1.2" polyphen="2.2.2" regbuild="1.0" sift="sift5.2.2"
```
Check if the following sandbox links show the expected information compared …

Display VEP data version in web VEP (109)

---

tools_hive/modules/EnsEMBL/Web/RunnableDB/VR.pm

Check if spdi is defined in the hash before trying to try it to the output. 
This check is already being done for the other types.
Variant to test: HBB:c.270T>R

Variant Recoder - check if spdi is defined in output

---

ensembl/conf/json/ovis_aries_rambouillet_vcf.json

[ENSVAR-4075](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4075): VCF files were remapped from sheep texel LD populations. This PR allows Sheep rambouillet to use the remapped VCF files to display LD data in web: [sandbox example](http://wp-np2-11.ebi.ac.uk:6070/Ovis_aries_rambouillet/Location/LD/ajax?db=core;r=1%3A124145-126818;pop1=153;pop2=142;pop3=132)
Related with https://github.com/Ensembl/ensembl-variation/pull/908

Add VCF files for LD populations in sheep Rambouillet (e109)

---

docs/htdocs/info/docs/tools/vep/script/vep_plugins.html
tools/conf/vep_plugins_web_config.txt

* Mention support for VEP plugins in Docker image
* Mention that some plugins are available in REST
* Remove mention to external UTRannotator plugin (we now include it in VEP_plugins repo)
The changes are reflected in my [sandbox](http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/script/vep_plugins.html).

Update VEP plugins docs (109)

---

docs/htdocs/info/docs/tools/vep/script/vep_options.html

[ENSVAR-5301](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5301): Documented VEP arguments `--ga4gh_vrs` and `--ambiguous_hgvs`.
Check documentation changes in my [sandbox](http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/script/vep_options.html#opt_hgvs).

Document VEP flags missing from public docs

---

ensembl/modules/EnsEMBL/Web/Document/HTML/ConsequenceTable.pm

The impact of '**regulatory_region_ablation**' should be **MODIFIER** instead if **MODERATE**.
http://wp-np2-11.ebi.ac.uk:7070/info/genome/variation/prediction/predicted_data.html

Fix impact for a consequence (e109)

---

ensembl/conf/ini-files/nomascus_leucogenys.ini
ensembl/conf/json/microtus_ochrogaster_vcf.json
ensembl/conf/json/nomascus_leucogenys_vcf.json

[ENSVAR-5465](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5465): Configure VCF for Gibbon
[ENSVAR-5432](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5432): Configure VCF for Prairie vole
Related with https://github.com/Ensembl/ensembl-variation/pull/952
Test in my sandbox:
* Gibbon:
* [Track with EVA variants](http://wp-np2-11.ebi.ac.uk:6070/Nomascus_leucogenys/Location/View?r=22a%3A10991516-11060966)
* [Variant example in species page](http://wp-np2-11.ebi.ac.uk:6070/Nomascus_leucogenys/Info/Index)
* Prairie vole:
* [Track with EVA variants](http://wp-np2-11.ebi.ac.uk:6070/Microtus_ochrogaster/Location/View?r=1:14087750-14088900;db=core)
* [Variant example in species page](http://wp-np2-11.ebi.ac.uk:6070/Microtus_ochrogaster/Info/Index)

Fetch EVA variants for Gibbon and Prairie vole (e110)

---

tools/modules/EnsEMBL/Web/Component/Tools/VR/InputForm.pm

MANE select option in Variant Recoder was being displayed for all species, despite it only being available for human in the data. An initial attempt was made at fixing this in #655. However, @jyobhai identified that the issue could break other parts of the site and is not the right solution. Hence, another attempt at fixing this.
On the Perl side, the reason why MANE select option was not toggleable was because it gets added only when homo sapiens is selected by default for Variant Recoder. This has been fixed in this pull request.
On the JavaScript side, the escape code for the species class names was escaping them where not necessary as well. This was breaking the code and not showing/toggling the relevant options in tools forms. This has been fixed in a pull request for …

Display MANE select option only for human in Variant Recorder

---

ensembl/htdocs/info/website/archives/ssi/about.html

This change is to remove the statement "Currently all databases are available from 2004." from the archive page as described in https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6682
The change can be viewed here http://wp-np2-1f.ebi.ac.uk:10000/info/website/archives/index.html

ENSWEB-6682 - Removed database availability statement

---

tools_hive/conf/vep_plugins_hive_config.txt

Update version for release 110.
SpliceAI ensembl_mane files are only available for grch38.

Update Mastermind and SpliceAI file version (e110)

---

tools/modules/EnsEMBL/Web/Component/Tools/VEP/Results.pm

As we read the VEP file row by row, we generate a `$row` hash ([link](https://github.com/Ensembl/public-plugins/blob/88a5a1a840f70fe7ec9af11b6f0a43854acd3db2/tools/modules/EnsEMBL/Web/Component/Tools/VEP/Results.pm#L235)), but then, counterintuitively, mutate it ([link](https://github.com/Ensembl/public-plugins/blob/88a5a1a840f70fe7ec9af11b6f0a43854acd3db2/tools/modules/EnsEMBL/Web/Component/Tools/VEP/Results.pm#L247)), so that the `Gene` field of the hash that used to contain a gene id is replaced with a string of an html link. For example, before the mutation, $row->{Gene} is `Os01g0100100`, but after the mutation it becomes `<a class="_zmenu" href="/Oryza_sativa/Gene/Summary?db=core;g=Os01g0100100;tl=BroHokEyP7tQRoxJ-2146">Os01g0100100</a><a class="hidden _zmenu_link" …

Fix link to VEP Alphafold page

---

tools/conf/vep_plugins_web_config.txt
tools/modules/EnsEMBL/Web/Component/Tools/VEP/InputForm.pm
tools/modules/EnsEMBL/Web/Component/Tools/VEP/Results.pm
tools/modules/EnsEMBL/Web/VEPConstants.pm
tools_hive/conf/vep_plugins_hive_config.txt

[ENSVAR-5485](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5485): add functionality of [MaveDB plugin](https://github.com/Ensembl/VEP_plugins/pull/604) to web VEP and properly format web VEP results
We decided to only show unique links to MaveDB for now, in contrast with the results from using VEP in CLI or REST that show more detailed information. This is most likely subject to change in future Ensembl releases.
- Ensembl/VEP_plugins#604
- https://github.com/Ensembl/ensembl-webcode/pull/967
You can test the following variants in [my dev sandbox](http://wp-np2-11.ebi.ac.uk:6070/Tools/VEP) by enabling MaveDB plugin:
```
16      1314031 .       A       T
16      1314056 .       T       A
16      1324785 .       CCC     TTT
```

Add MaveDB plugin to web VEP (110)

---

docs/htdocs/info/docs/tools/vep/vep_formats.html

Related with https://github.com/Ensembl/ensembl-vep/pull/1370 and https://github.com/Ensembl/ensembl-vep/pull/1399
- Standardise supported SV types across default VEP input, REST-style regions and VCF
- Mention CNV support for `<CN=3>`-like format
- Mention breakend support
- Add more SV examples
- Copy-edit documentation
Check changes in my sandbox: http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/vep_formats.html

Document improvements to SV input in VEP (e110)

---

docs/htdocs/info/docs/tools/vep/script/vep_options.html
docs/htdocs/info/docs/tools/vep/vep_formats.html

Added a flag for `--uploaded_allele` and an output column `UPLOADED_ALLELE`
Updated description for `--show_ref_allele` and `REF_ALLELE` output column 
VEP options: http://wp-np2-25.ebi.ac.uk:6080/info/docs/tools/vep/script/vep_options.html
VEP format: http://wp-np2-25.ebi.ac.uk:6080/info/docs/tools/vep/vep_formats.html#output

Added docs for uploaded_allele flag (e110)

---

tools/modules/EnsEMBL/Web/Component/Tools/VEP/InputForm.pm
tools/modules/EnsEMBL/Web/VEPConstants.pm

[ENSVAR-5913](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5913)
For species-specific plugins, we currently add a `_stt_[Species_name]` class to the plugin option elements (such as `_stt_Homo_sapiens`) so that the option is only shown if that species is currently selected.
However, when using a different division of Ensembl (e.g., plants), if the species is not present in `$self->object->species_list`, the class is ignored and the plugin options are displayed for all species in that division.
This PR solves this issue by checking if any of the supported species is available in the species list for this division. If the species is not in the list, then we don't add the plugin options.
- **Splicing predictions** are hard-coded to be only available for human. This was fixed by stating the …

Fix VEP input form showing unsupported plugin options in wrong divisions (e111)

---

tools/modules/EnsEMBL/Web/Component/Tools/VEP/InputForm.pm

After merging #712 and #716, the web VEP input form ended up with redundant code for the 'Variant data' section.
This PR intends to remove the redundant code.
Check results in my sandbox: http://wp-np2-11.ebi.ac.uk:6070/Multi/Tools/VEP?db=core

Web VEP: remove redundant 'Variant data' section code (e111)

---

docs/htdocs/info/docs/tools/vep/script/vep_custom.html

Fixes Ensembl/ensembl-vep#1453
In VEP 110, we improved `--custom` to support a more flexible approach with key-value pairs. This change is incompatible with VEP 109 and earlier.
In this PR, we add the usage documentation for these older versions of VEP so they are still easily available to all users, as requested by a user in Ensembl/ensembl-vep#1453.
- Re-introduce 109 docs for `--custom` usage
- This section is virtually the same from 109 docs: https://github.com/Ensembl/public-plugins/blob/release/109/docs/htdocs/info/docs/tools/vep/script/vep_custom.html#L139-L235.
- The usage of positional arguments (like in older VEP versions) is still compatible with VEP 110 and newer.
- Update the section regarding the modern usage of `--custom` to:
- emphasise the advantages of using key-value …

Document `--custom` usage for older versions of VEP (e111)

---

docs/htdocs/info/docs/tools/vep/vep_formats.html

Related with Ensembl/ensembl-vep#1478
- Mention structural variant (SV) support for variant identifiers
- Add examples of SVs in the table at the top
- Update examples (some HGVS ones were not working)
- Remove mentions to LRG
Check changes in my sandbox: http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/vep_formats.html#hgvs

VEP docs: update VEP input format examples

---

tools/conf/ini-files/MULTI.ini

This PR removes the options in the blast submission for that allow the user to search against databases of abinitio genes. These genesets are no longer generated and when the user chooses that option for a species that doesn't have them, the website reports an error. 
See [ENSWEB-6914](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6914) for more details.

Remove references to abinitio DBs from MULTI.ini

---

docs/htdocs/info/docs/tools/vep/script/vep_options.html

Check changes in my sandbox: http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/script/vep_options.html#opt_summary
- Fix table overflow by breaking words in `pre` tags
- Add background colour to distinguish global populations in `--freq_pop`
- Add missing column in `--synonyms`

Improve VEP options table

---

docs/htdocs/info/docs/tools/vep/script/vep_example.html
ensembl/htdocs/info/genome/variation/prediction/protein_function.html
tools_hive/conf/vep_plugins_hive_config.txt

[ENSVAR-6120](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6120)
- Update dbNSFP data version in public docs
- Update file path
- Update dbNSFP example docs
- Check publics docs changes in [vep_example.html#dbNSFP](http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/script/vep_example.html#dbNSFP)
- Test VEP in my [sandbox](http://wp-np2-11.ebi.ac.uk:6070/Homo_sapiens/Tools/VEP/Results?tl=ca60xPCVe96wi7ZG-109); only supports dbNSFP variants in chromosome 18, such as:
```
rs1208893863
rs1243334743
rs1276354422
rs1318597724
rs1348242192
rs1441742077
rs1477215563
rs1489182805
rs1905642714
rs1905645225
rs1905647878
rs529943330
rs543847261
rs562842438
```

VEP plugin: Update to dbNSFP 4.5c data (e112)

---

docs/htdocs/info/docs/tools/vep/online/input.html
tools/conf/vep_plugins_web_config.txt
tools_hive/conf/vep_plugins_hive_config.txt

[ENSVAR-6046](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6046)
Plugin disabled in GRCh37: https://github.com/Ensembl/ebi-plugins/pull/168
- Documentation update: http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/online/input.html
- Web VEP: http://wp-np2-11.ebi.ac.uk:6070/Homo_sapiens/Tools/VEP/Results?tl=6RmHUye4v10akm1c-115
Example of variant for RiboseqORFs:
```
1 119140608 rs139548132 A C,G,T
```

Add plugin RiboseqORFs to web VEP (e112)

---

ensembl/htdocs/info/genome/funcgen/data/accessing-regulation.html
ensembl/htdocs/info/genome/funcgen/process/humanandmouse/segmentation.html

Documentation has been updated to reflect the removal of segmentation tracks in 112, as well as other updates, including label changes.
Sandbox URL:
Documentation is currently available on http://wp-np2-11.ebi.ac.uk:6010/info/genome/funcgen/index.html.

Update regulation docs for 112

---

docs/htdocs/info/docs/tools/vep/script/vep_filter.html

[ENSVAR-6233](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6233)
A clear comment on separator would help users. 
sandbox link - http://wp-np2-11.ebi.ac.uk:7070/info/docs/tools/vep/script/vep_filter.html#filter_write

Make clear comment in the document on separator for filter_vep (e112)

---

docs/htdocs/info/docs/tools/vep/script/vep_cache.html

Update bacterial VEP cache link to point to indexed cache
Check changes in my sandbox: http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/script/vep_cache.html#cache

Update indexed VEP cache links (bacteria)

---

widgets/htdocs/alphafold/components/confidenceMissenseToggle.js
widgets/htdocs/alphafold/components/ensemblAlphafoldMissense.js
widgets/htdocs/alphafold/components/ensemblAlphafoldProtein.js
widgets/htdocs/alphafold/components/ensemblAlphafoldVep.js
widgets/htdocs/alphafold/components/missenseColorsPanel.js
widgets/htdocs/alphafold/controllers/confidenceMissenseController.js
widgets/htdocs/alphafold/controllers/missenseController.js
widgets/htdocs/alphafold/controllers/molstarController.js

This PR adds a missense visualisation to the transcript and vep mol* protein view.
Transcript view of missense
http://wp-np2-1f.ebi.ac.uk:10000/Homo_sapiens/Transcript/AFDB?g=ENSG00000113282;r=5:157785747-157859145;t=ENST00000411809
Vep view of missense
http://wp-np2-1f.ebi.ac.uk:10000/Homo_sapiens/Tools/VEP/AFDB?cons=missense_variant;g=ENSG00000162551;pos=123;r=1:21509397-21578410;t=ENST00000374840;tl=oC7nwlZwvyXywnvd-20;var=rs1188506084
Vep view where missese is not available 
http://wp-np2-1f.ebi.ac.uk:10000/Homo_sapiens/Tools/VEP/AFDB?cons=missense_variant;g=ENSG00000186092;pos=2;r=1:65419-71585;t=ENST00000641515;tl=4OC8idHwqqeHacfV-18;var=.

Added missense support to alphafold

---

tools/modules/EnsEMBL/Web/Component/Tools/VEP/Results.pm

Update the alphafold prefix that will be included in VEP results in 112.
The reason the prefix changed from `AFDB-ENSP_mappings` to `AlphaFold_DB_import` is because it was hard-coded this way in the pipeline updated by the Infrastructure team. The correct behaviour should be for the pipeline to get the analysis name from a production database. This should be corrected in e113. Meanwhile, since the `AlphaFold_DB_import` string has now been saved into VEP caches, the simplest thing to do for e112 is to change the string that web code matches.
This change is intended to only go into the 112 release branch, and should then be pushed to www and plants sites that have VEP with Alphafold.
Sandbox: http://wp-np2-1e.ebi.ac.uk:8410/Homo_sapiens/Tools/VEP/Results?tl=o7aod5zBdFqdsi65-25

Update Alphafold prefix used in VEP cache for e112

---

docs/htdocs/info/docs/tools/vep/script/index.html
docs/htdocs/info/docs/tools/vep/script/vep_example.html
docs/htdocs/info/docs/tools/vep/vep_formats.html

[ENSVAR-6222](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6222)
Check changes in my sandbox:
- http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/vep_formats.html#sv
- http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/script/index.html
- http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/script/vep_example.html#StructVar

VEP: Improve documentation on SV support

---

tools/modules/EnsEMBL/Web/Job/VEP.pm
tools/modules/EnsEMBL/Web/Object/VEP.pm

Currently we [update INI files](https://github.com/Ensembl/public-plugins/pull/754) to setup species with regulatory build in web VEP. But it can be directly derived from the species def config tree.
The target of this update is in e113 - regulation will review the [summary data](https://github.com/Ensembl/ensembl-webcode/blob/25c16dc3ff2135b5e3b31e0ad186113bb25194d3/modules/EnsEMBL/Web/ConfigPacker.pm#L699) loaded in the species defs first [confirmed].
test sandbox url - http://wp-np2-11.ebi.ac.uk:7070/Tools/VEP
Test can be done for `turbot`, `european seabass` on example variants.

Check config tree instead of INI for regulation species (e113)

---

docs/htdocs/info/docs/tools/vep/online/input.html
docs/htdocs/info/docs/tools/vep/script/vep_options.html

The mirna flag doesn't work for refseq transcripts and no trivial way to add this functionality, so we will indicate that it's only suported for Ensembl/genocde

Fixing miRNA docs

---

ensembl/htdocs/ssi/species/Sus_scrofa_bamei_annotation.html

There are some copy-paste errors in the Bamei Pig breed info text.
This PR applies a similar fix to the Bamei Pig breed as was previously applied to other affected Pig breeds ([commit a1c23bd](https://github.com/Ensembl/public-plugins/commit/a1c23bdcf6b32318a6fe77268644caa6de037eef)).
Example on sandbox: http://wp-np2-25.ebi.ac.uk:5092/Sus_scrofa_bamei/Info/Annotation
Example on staging: https://staging.ensembl.org/Sus_scrofa_bamei/Info/Annotation

Fix some copy-paste errors in Bamei Pig breed info

---

docs/htdocs/info/docs/tools/vep/online/input.html
tools/conf/vep_plugins_web_config.txt
tools_hive/conf/vep_plugins_hive_config.txt

[ENSVAR-6395](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6395): add ClinPred plugin to web VEP + REST
[ENSVAR-6396](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6396): add REVEL plugin to web VEP + REST
Requires https://github.com/Ensembl/VEP_plugins/pull/729
Test in my [sandbox](http://wp-np2-11.ebi.ac.uk:6070/Homo_sapiens/Tools/VEP/Results?tl=YdC3TIKeMhDHfy3s-1) with these examples:
```
11 168962 168962 T A
20 68351 87710 A C
22 15690303 15690303 C A
22 17071770 16590880 G C
```
Check documentation updates in http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/online/input.html

Web VEP: Add REVEL and ClinPred plugins

---

docs/htdocs/info/docs/tools/vep/script/vep_options.html

Some slightly incorrect text for symbols option, expanded to specify that ensembl or merged cache is fine (but not refseq).

HGNC doc fix

---

docs/htdocs/info/docs/tools/vep/script/vep_cache.html

Non indexed caches are not really required any more and the doc can be a bit confusing. Everyone should be using the tabix'd versions now.

Removing old text

---

docs/htdocs/info/docs/tools/vep/script/vep_custom.html
docs/htdocs/info/docs/tools/vep/script/vep_options.html
docs/htdocs/info/docs/tools/vep/script/vep_plugins.html

[ENSVAR-5412](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5412): Document missing VEP flags
* Document `--safe` flag in VEP
* Improve plugin docs
* Add example on conservation scores in VEP custom annotation
Check my sandbox in the following pages:
- http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/script/vep_options.html
- http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/script/vep_custom.html#remote_custom_example
- http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/script/vep_plugins.html

Document missing VEP flags

---

tools/modules/EnsEMBL/Web/Component/Tools/VEP/InputForm.pm
tools/modules/EnsEMBL/Web/Job/VEP.pm

Subsequent VEP job retains job data from previous job in the same session. It probably is an old business rule to retain the options the user selected previously to give better experience.
It becomes a problem if the subsequent job is run on different species. The job data can retain information about features that the species does not have. For example in the following run on rainbow tout -
http://www.ensembl.org/Oncorhynchus_mykiss/Tools/VEP/Results?tl=bpeS1USpYURvU7l3-10317182 
the job data retained information about frequency options used in previous run using goat. That is why we are seeing frequency headers in the output even though user did not select any frequency option (in fact there was no frequency option).
This is an old issue, and also affects the _**plugins**_.
Check if …

VEP cached jobdata - refrain submitting plugin/custom unless matched species (e113)

---

docs/htdocs/info/docs/tools/vep/online/input.html
docs/htdocs/info/docs/tools/vep/script/vep_download.html
tools/conf/vep_plugins_web_config.txt
tools/modules/EnsEMBL/Web/Component/Tools/VEP/Results.pm
tools_hive/conf/vep_plugins_hive_config.txt

[ENSVAR-6290](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6290)
Test in my sandbox:
- Documentation changes:
- [Web VEP input docs](http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/online/input.html#freq)
- [What's new in VEP](http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/online/download.html#new)
- [Web VEP](http://wp-np2-11.ebi.ac.uk:6070/Multi/Tools/VEP?db=core)
- [Results example](http://wp-np2-11.ebi.ac.uk:6070/Homo_sapiens/Tools/VEP/Results?from=1;size=12;tl=NmXCXfSwVTsg7glP-23;to=12)
In web VEP, you can test with the following variants (not all chromosomes are available in my sandbox):
```
1 18108132 . A T
11 99556218 . G C
19 110682 . T G
20 87737 . C G
20 325925 . A T
22 15528369 . T G
22 15528390 . T G
22 15528213 . A C
22 15528195 . T G
X 630901 . A T
X 630907 . T C …
```

Add Paralogues plugin to web VEP (e113)

---

docs/htdocs/info/docs/tools/vep/script/vep_download.html

link: http://wp-np2-11.ebi.ac.uk:7070/info/docs/tools/vep/script/vep_download.html#new (ignore the version)

Add LOEUF plugin update in vep what's new (e113)

---

docs/htdocs/info/docs/tools/vep/script/vep_download.html

We have added the following libraries in our API code at some point is previous releases -
-[ LWP::Simple](https://github.com/Ensembl/ensembl-vep/blob/31a3581b84495b617b2f3980da6c6313ca6d238f/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm#L73)
-[ List::MoreUtils](https://github.com/Ensembl/ensembl-vep/blob/31a3581b84495b617b2f3980da6c6313ca6d238f/modules/Bio/EnsEMBL/VEP/Parser/VCF.pm#L82)
We should add them to the dependency list in the installation instruction in the public docs

Add missing perl library dependencies needed to run VEP (e114)

---

tools/modules/EnsEMBL/Web/JSONServer/Tools/VEP.pm

https://www.ebi.ac.uk/panda/jira/browse/ENSINT-2018
sandbox url - http://wp-np2-11.ebi.ac.uk:7070/Tools/VEP - check sheep texel not available in species list.

Remove sheep texel from web VEP

---

docs/htdocs/info/docs/tools/vep/script/index.html
docs/htdocs/info/docs/tools/vep/script/vep_download.html

Add new section on Nextflow VEP regarding e114 changes.
The commands work at the moment because of the `-r main` option used, but since the changes will only be officially part of VEP e114, I think we should delay the documentation to e114 as well.
Check my sandbox: http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/script/vep_download.html#nextflow

VEP docs: add Nextflow section (e114)

---

ensembl/conf/ini-files/mus_musculus_lpj.ini
ensembl/conf/ini-files/mus_musculus_nzohlltj.ini

This PR comes with my apologies.
[public-plugins PR 838](https://github.com/Ensembl/public-plugins/pull/838) included two errors: one in the configuration of Mouse strain LP/J, the other in the configuration of Mouse strain NZO/HlLtJ.
This PR would fix both configuration errors.
Examples:
- Mouse LP/J: [sandbox](http://wp-np2-25.ebi.ac.uk:5092/Mus_musculus_LP_J/Info/Index) vs [staging](https://staging.ensembl.org/Mus_musculus_LP_J/Info/Index)
- Mouse NZO/HlLtJ: [sandbox](http://wp-np2-25.ebi.ac.uk:5092/Mus_musculus_NZO_HlLtJ/Info/Index) vs [staging](https://staging.ensembl.org/Mus_musculus_NZO_HlLtJ/Info/Index)

Fix Mouse strain genome config for e114

---

tools_hive/conf/SiteDefs.pm
tools_hive/modules/EnsEMBL/Web/JobDispatcher/Hive.pm
tools_hive/modules/EnsEMBL/Web/RunnableDB/VEP.pm
tools_hive/modules/EnsEMBL/Web/ToolsPipeConfig.pm
tools_hive/modules/EnsEMBL/Web/ToolsPipeConfig/AlleleFrequency.pm
tools_hive/modules/EnsEMBL/Web/ToolsPipeConfig/AssemblyConverter.pm
tools_hive/modules/EnsEMBL/Web/ToolsPipeConfig/Blast.pm
tools_hive/modules/EnsEMBL/Web/ToolsPipeConfig/Blat.pm
tools_hive/modules/EnsEMBL/Web/ToolsPipeConfig/DataSlicer.pm
tools_hive/modules/EnsEMBL/Web/ToolsPipeConfig/FileChameleon.pm
tools_hive/modules/EnsEMBL/Web/ToolsPipeConfig/IDMapper.pm
tools_hive/modules/EnsEMBL/Web/ToolsPipeConfig/LD.pm
tools_hive/modules/EnsEMBL/Web/ToolsPipeConfig/VEP.pm
tools_hive/modules/EnsEMBL/Web/ToolsPipeConfig/VR.pm
tools_hive/modules/EnsEMBL/Web/ToolsPipeConfig/VariationPattern.pm
tools_hive/modules/EnsEMBL/Web/ToolsPipeConfig/VcftoPed.pm
tools_hive/utils/beekeeper.pl
tools_hive/utils/beekeeper_manager.pl

The changes in this PR are part of switching `ensembl-hive` from version 2.2 to version 2.7, and of migration from LSF to Slurm. They include:
- Updates to `beekeeper_manager.pl` to stop it from passing arbitrary command-line options to `beekeeper.pl` (beekeeper.pl in ensembl-hive, which is the script that is eventually called, no longer allows options outside of the ones that it expects).
- Updates to `beekeeper.pl` to fix a problem when it would call itself. You will notice that the old version of `beekeeper.pl` has a `do` command, with which it calls `beekeeper.pl` in `ensembl-hive`. For some reason that remains a mystery, after we switched ensembl-hive to version 2.7, our `beekeeper.pl` (i.e. the one in the public-plugins repo) started calling itself at the `do` line instead of …

Tools hive: LSF to Slurm migration

---

docs/htdocs/info/docs/tools/vep/script/vep_download.html

sandbox url - http://wp-np2-11.ebi.ac.uk:7070/info/docs/tools/vep/script/vep_download.html#opt_use_https_proto
required by - https://github.com/Ensembl/ensembl-vep/pull/1805

Update VEP install doc for new options (114)

---

genoverse/modules/EnsEMBL/Web/ImageConfig/Genoverse.pm

Add Gencode Primary track to Region in Detail and make it enabled by default. Users will still be able to switch/enable Gencode Basic track. I used #833 as reference when working on this.
**Release version:** 114
**Sandbox link:** http://wp-np2-1e.ebi.ac.uk:8310/Homo_sapiens/Location/View?db=core;g=ENSG00000139618;r=13:32315086-32400268
**Related PR:** https://github.com/Ensembl/ensembl-webcode/pull/1060

Add Gencode Primary Track to Region in Detail

---

docs/htdocs/info/docs/tools/vep/script/vep_custom.html

VEP custom annotation allows to give multiple files split by chromosome using `###CHR###` value but not documented. This PR document this feature.
sandbox url - http://wp-np2-11.ebi.ac.uk:7070/info/docs/tools/vep/script/vep_custom.html

Document multiple chromosome files feature in VEP custom annotation (e114)

---

genoverse/modules/EnsEMBL/Web/Controller/Genoverse.pm

This PR fixes the bug that was introduced in https://github.com/Ensembl/ensembl-webcode/pull/1060, during the modifications to support the GENCODE Primary transcript set.
**PROBLEM:** Transcripts within the Gencode Basic and Gencode Primary tracks started showing up in red (compare on screenshot below with transcripts from the Gencode Comprehensive track):
**CAUSE:** 
- In https://github.com/Ensembl/ensembl-webcode/pull/1060, the `_gencode.pm` module was renamed and split into `_gencode_basic.pm` and `_gencode_primary.pm`. The url of the network requests to fetch data for these tracks has also changed from `https://www.ensembl.org/Homo_sapiens/Genoverse/fetch_features/_gencode?config=contigviewtop&id=gencode&renderer=gene_label&db=core&r=17:62384780-65515519` to …

Fix display of gencode primary and gencode basic transcripts in Genoverse

---

solr/conf/SiteDefs.pm

As part of [ENSWEBREL-1033](https://www.ebi.ac.uk/panda/jira/browse/ENSWEBREL-1033), updated the list of strains/breeds for search.
Based on the output of the dumping script:
```
There are 346 species
Dumping xml files to input
Species canis_lupus_familiarisbasenji has strains, with parent of Dog
Species canis_lupus_familiarisboxer has strains, with parent of Dog
Species canis_lupus_familiarisgreatdane has strains, with parent of Dog
Species canis_lupus_familiarisgsd has strains, with parent of Dog
Species capra_hircus_blackbengal has strains, with parent of Goat
Species capra_hircus_gca015443085v1 has strains, with parent of Goat
Species capra_hircus_gca026652205v1 has strains, with parent of Goat
Species felis_catus_abyssinian has strains, with parent of Domestic cat
Species …
```

Update strains/breeds in Solr config for e114

---

tools/conf/vep_custom_web_config.json
tools_hive/conf/vep_plugins_hive_config.txt
tools_hive/modules/EnsEMBL/Web/RunnableDB/VEP.pm

We use ###CHR### placeholder in VEP custom annotation to allow annotating from multiple file. But as web VEP job submission happen via eHive and eHive has a logic to param replacement with anything #TOKEN# it is creating failure.
The solution tried here is to escape # in the ###CHR### in the custom config with double backlash and replace them back again before submitting the VEP job.
Need for using double backlash -
- The config JSON is read by using Perl JSON module and it cannot parse a single backlash in the config.
Need for replacing the backlash again
- VEP can support ###CHR### or an escaped version with single backlash \#\#\#CHR\#\#\# but perl JSON module converts \\ --> \\ (not single backlash). That's we need to replace them back again.
sandbox test url - …

Avoid hive param_substitute in VEP custom config (114)

---

tools/conf/vep_custom_web_config.json

We had to remove the `max_subpop` field for AllOfUs option in web VEP because they were missing from the data in this PR - https://github.com/Ensembl/public-plugins/pull/868
With the addition of this data we are adding back the field.
sandbox url for test - 
http://wp-np2-35.ebi.ac.uk:7070/Homo_sapiens/Tools/VEP/Results?tl=nStkHAdk33R9mNrs-62

Add back max subpop column for AllOfUs in web VEP - 115

---

ensembl/htdocs/Mus_musculus_strains.inc

I have updated the total number of strains in the Mus_musculus_strains.inc document, in light of the Murinae EPO update for release 115.

Updating the number of Mus musculus strains

---

tools/conf/vep_custom_web_config.json
tools/modules/EnsEMBL/Web/Component/Tools/VEP/InputForm.pm
tools/modules/EnsEMBL/Web/Component/Tools/VEP/Results.pm

example sandbox url: http://wp-np2-35.ebi.ac.uk:7070/Homo_sapiens/Tools/VEP/Results?tl=LlPKWfcJ4D2ddHA4-46
- option name - "gnomAD_SV allele frequencies"
- the option is put under "Variants and frequency data" section
example sandbox url: 
http://wp-np2-35.ebi.ac.uk:7070/Homo_sapiens/Tools/VEP/Results?tl=JQxJ2Ojmo7SILXxd-57
(somatic) http://wp-np2-35.ebi.ac.uk:7070/Homo_sapiens/Tools/VEP/Results?tl=Y5zvqYwNa2stuk0d-58
- option name - "Clinical Significance (SV)"  and "Clinical Significance (somatic SV)"
- the option is put under "Phenotype and citation data" section
- following fields are picked for display -
- `CLNSIG` - clinical significance
- `CLNACC` - accession number (from ClinVar)
- `clinical_source` - source of clinsig
-  `REGIONID` - dbVar parent region ID
- `ORIGIN` - cell …

Add gnomAD and Clinical SV custom annotation for web VEP - 115

---

ensembl/htdocs/info/genome/compara/analyses.html
ensembl/htdocs/info/genome/compara/ancestral_sequences.html
ensembl/htdocs/info/genome/compara/conservation_and_constrained.html

Some compara doc fixes:
- "Ancestral sequences" page updated with current Vertebrates ancestral-sequence name example.
- "Conservation scores" page updated to include pig breeds EPO_EXTENDED in list of multiple alignments.
- "Analyses" page updated to reflect the fact that BlastZ is no longer used in practice.
Related tickets:
- ENSCOMPARASW-8492
- ENSCOMPARASW-8487
- ENSCOMPARASW-8485

Various compara documentation fixes

---

ensembl/htdocs/info/genome/compara/accessing_compara.html

This PR would add the Ensembl REST API to the list of ways to access Compara data.

Add Ensembl REST API to list of ways to access Compara data

---

ensembl/htdocs/index.html
ensembl/htdocs/info/index.html

- Replacing home page text about Ensembl with the agreed text
- Removal of additional descriptions of mission instead relying on the about page to convey this

Inline with feedback from our SAB we are clarifying our mission
