- widgets/htdocs/widgets/96_CafeTree.js
A quick fix to always display the p-value
> Always display the p-value

- ensembl/htdocs/info/genome/microarray_probe_set_mapping.html
> corrected typo in microarray_probe_set_mapping.html

- ensembl/conf/ini-files/DEFAULTS.ini
> Tree shrew was not counted as a placental mammal. Now in the category "Rodents etc"

- ensembl/htdocs/info/about/code_of_conduct.html
- ensembl/htdocs/info/about/contact/mailing.html
This is our official description of a code of conduct for all communication with Ensembl. Let me know if this is ok to integrate.
> Adding code of conduct.

- widgets/modules/EnsEMBL/Web/Component/Gene/SpeciesTree.pm
cf https://github.com/Ensembl/ensembl-webcode/pull/372
> [CAFE view] Use the precomputed JSON

- ensembl/htdocs/info/genome/compara/analyses.html
- ensembl/htdocs/info/genome/compara/index.html
Changes related to ensembl-webcode#386
> Compara stats

- ensembl/htdocs/info/about/publications.html
- ensembl/htdocs/info/genome/compara/analyses.html
- ensembl/htdocs/info/genome/compara/index.html
- ensembl/htdocs/info/genome/compara/ncRNA_methods.html
> Compara doc update

- tools/htdocs/components/20_BlastForm.js
It may contain characters like commas or spaces.  Similar to b7a4335b32798933dfe872f7a7cfdeee1cd0e0e0
(Merging on correct branch, as requested in #58)
> Need to quote the option value in find expression

- widgets/htdocs/widgets/96_CafeTree.js
Request from Paul K.
See it working at http://enssand-01.internal.sanger.ac.uk:9073/Homo_sapiens/Gene/SpeciesTree?db=core;g=ENSG00000139618;gtr=order;r=13:32315474-32400266
> Added a link to the CAFE publication

- ensembl/htdocs/info/genome/compara/nc_tree_stats.html
- ensembl/htdocs/info/genome/compara/prot_tree_stats.html
Comes with Ensembl/ensembl-webcode#498
> Corrections suggested by Paul K.

- docs/htdocs/info/about/legal/disclaimer.html
- ensembl/htdocs/info/about/credits.html
- ensembl/htdocs/info/about/index.html
Issue originally raised in ENSWEB-4136. We should get this out before 90 if possible
> Remove WTSI references

- tools/modules/EnsEMBL/Web/Component/Tools/LD/InputForm.pm
- tools/modules/EnsEMBL/Web/Component/Tools/LD/Results.pm
- tools/modules/EnsEMBL/Web/Object/LD.pm
- tools/modules/EnsEMBL/Web/Ticket/LD.pm
- tools_hive/modules/EnsEMBL/Web/RunnableDB/LD.pm
PR addresses some issues which came up after testing tool's functionality more intensively.
> Ld tool/updates

- ensembl/htdocs/info/genome/variation/predicted_data.html
> Added SIFT and Polyphen threshold tables

- tools/modules/EnsEMBL/Web/Component/Tools/LD/InputForm.pm
- tools/modules/EnsEMBL/Web/Object/LD.pm
I had a quick look at test.ensembl and noticed a bug in my code. Will be fixed with this PR. I also changed image display parameters.
> Ld tool/updates3

- ensembl/modules/EnsEMBL/Web/Document/HTML/ConsequenceTable.pm
Corrected description to description for SO term (SO:0001907)
> Correct description for feature_elongation

- tools/modules/EnsEMBL/Web/Component/Tools/VEP/TicketDetails.pm
> update VEP command

- docs/htdocs/info/docs/tools/vep/vep_formats.html
Added ambiguity flag into CL and REST VEP. Changes to ensembl-vep, ensembl-rest and public_plugins have all been made at the same time.
> Added ambiguity flag into docs

- tools_hive/modules/EnsEMBL/Web/RunnableDB/LD.pm
post release fix for LD calculator
> update method names for getting variation feature location information

- ensembl/htdocs/ssi/species/Callithrix_jacchus_annotation.html
- ensembl/htdocs/ssi/species/Callithrix_jacchus_assembly.html
I've updated all the info for web page for Marmoset to reflect the new assembly
Thanks
> New web descriptions for Marmoset

- tools/modules/EnsEMBL/Web/Component/Tools/LD/Results.pm
- tools/modules/EnsEMBL/Web/Object/LD.pm
- tools/modules/EnsEMBL/Web/Ticket/LD.pm
- tools_hive/modules/EnsEMBL/Web/RunnableDB/LD.pm
Some updates for release/92
-Add a download all button
-Trim input from any whitespace that could cause problems when reading the input data
-only use variants located on the reference genome excluding haplotypes
> Ld tool updates 92

- ensembl/htdocs/info/genome/variation/predicted_data.html
Condel text has been removed from here as it is no longer supported in the API.
> remove Condel citation

- ensembl/htdocs/info/about/outreach/geek4aweek.html
Adding in new section but based changes against postreleasefix/92
> New section concerning non-disclosure agreements

- tools/modules/EnsEMBL/Web/Object/VEP.pm
Fix for https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-1214
> correct 1KG version in help

- tools/conf/vep_plugins_web_config.txt
- tools/htdocs/components/20_VEPForm.js
- tools/htdocs/components/70_vep.css
- tools/modules/EnsEMBL/Web/Component/Tools/VEP/InputForm.pm
- tools/modules/EnsEMBL/Web/Object/VEP.pm
- tools/modules/EnsEMBL/Web/VEPConstants.pm
- Updating the layout (grouping/splitting forms)
- Making the form more relevant, regarding the species selected (GENCODE option, Co-located variants, Regulation data, TSL, APPRIS, ...)
> Improve the VEP web input form

- tools/modules/EnsEMBL/Web/Component/Tools/VEP/InputForm.pm
same as #178, now against postreleasefix/95
> resolve cell type formatting conflict

- ensembl/conf/json/homo_sapiens_vcf.json
Update to new release r2.1 of gnomAD files. The files have been synced to ftp already.
> update gnomad to r2.1

- ensembl/conf/json/chlorocebus_sabaeus_vcf.json
This adds the track description.
> add description

- tools/conf/vep_plugins_web_config.txt
- tools/modules/EnsEMBL/Web/Component/Tools/VEP/InputForm.pm
- tools/modules/EnsEMBL/Web/Component/Tools/VEP/Results.pm
- tools_hive/conf/vep_plugins_hive_config.txt
Changes:
- added CADD (GRCh38 site) and Phenotypes plugins option to WEB VEP
- phenotypes plugin specific parameters
- update to the results display of phenotype results
> add Phenotypes and CADD plugins to WEB VEP

- ensembl/conf/json/bos_taurus_vcf.json
- ensembl/conf/json/canis_familiaris_vcf.json
- ensembl/conf/json/capra_hircus_vcf.json
- ensembl/conf/json/chlorocebus_sabaeus_vcf.json
- ensembl/conf/json/danio_rerio_vcf.json
- ensembl/conf/json/equus_caballus_vcf.json
- ensembl/conf/json/felis_catus_vcf.json
- ensembl/conf/json/gallus_gallus_vcf.json
- ensembl/conf/json/homo_sapiens_vcf.json
- ensembl/conf/json/macaca_mulatta_vcf.json
- ensembl/conf/json/meleagris_gallopavo_vcf.json
- ensembl/conf/json/mus_musculus_vcf.json
- ensembl/conf/json/nomascus_leucogenys_vcf.json
- ensembl/conf/json/ovis_aries_vcf.json
- ensembl/conf/json/pan_troglodytes_vcf.json
- ensembl/conf/json/pongo_abelii_vcf.json
- ensembl/conf/json/rattus_norvegicus_vcf.json
- ensembl/conf/json/sus_scrofa_vcf.json
- ensembl/conf/json/taeniopygia_guttata_vcf.json
- ensembl/conf/json/tetraodon_nigroviridis_vcf.json
I updated the path to use the release version. This will be important to get the correct data when checking archive sites.
> use release version

- tools/modules/EnsEMBL/Web/Component/Tools/VEP/Results.pm
- tools/modules/EnsEMBL/Web/Job/VEP.pm
Sandbox vep results link : http://ves-hx2-76.ebi.ac.uk:6080/Homo_sapiens/Tools/VEP/Results?db=core;tl=2xWPMVe3nQ1W3fJo-684
> Add transcript version to vep results - e97

- docs/htdocs/info/docs/tools/vep/script/vep_options.html
- docs/htdocs/info/docs/tools/vep/script/vep_other.html
> Docs update for --mane

- docs/htdocs/info/docs/api/core/core_schema.html
> Update Core schema diagrams for release 98

- ensembl/conf/json/bos_taurus_vcf.json
- ensembl/conf/json/canis_familiaris_vcf.json
- ensembl/conf/json/capra_hircus_vcf.json
- ensembl/conf/json/chlorocebus_sabaeus_vcf.json
- ensembl/conf/json/danio_rerio_vcf.json
- ensembl/conf/json/equus_caballus_vcf.json
- ensembl/conf/json/felis_catus_vcf.json
- ensembl/conf/json/gallus_gallus_vcf.json
- ensembl/conf/json/homo_sapiens_vcf.json
- ensembl/conf/json/macaca_mulatta_vcf.json
- ensembl/conf/json/meleagris_gallopavo_vcf.json
- ensembl/conf/json/mus_musculus_vcf.json
- ensembl/conf/json/nomascus_leucogenys_vcf.json
- ensembl/conf/json/ovis_aries_vcf.json
- ensembl/conf/json/pan_troglodytes_vcf.json
- ensembl/conf/json/pongo_abelii_vcf.json
- ensembl/conf/json/rattus_norvegicus_vcf.json
- ensembl/conf/json/sus_scrofa_vcf.json
- ensembl/conf/json/taeniopygia_guttata_vcf.json
- ensembl/conf/json/tetraodon_nigroviridis_vcf.json
Update to latest conservation file names for release/98
> GERP file version update

- docs/htdocs/info/docs/tools/vep/vep_faq.html
Some answers had A's, some didn't - standardised without.
>  VEP FAQ - add memory section + minor updates 

- ensembl/htdocs/ssi/species/Bos_indicus_hybrid_assembly.html
- ensembl/htdocs/ssi/species/Bos_taurus_hybrid_assembly.html
- ensembl/htdocs/ssi/species/Sus_scrofa_assembly.html
- ensembl/htdocs/ssi/species/Sus_scrofa_usmarc_assembly.html
Added publication links to html files for Sus scrofa, Bos indicus and Bos taurus hybrids
> Static content update

- ensembl/htdocs/ssi/species/Bos_indicus_hybrid_assembly.html
- ensembl/htdocs/ssi/species/Bos_taurus_hybrid_assembly.html
- ensembl/htdocs/ssi/species/Sus_scrofa_assembly.html
- ensembl/htdocs/ssi/species/Sus_scrofa_usmarc_assembly.html
Changed text and format to html files for Sus scrofa, Bos indicus and Bos taurus hybrids
> Formatting changes

- tools/htdocs/components/15_ToolsForm.js
- tools/modules/EnsEMBL/Web/Component/Tools/AlleleFrequency/Results.pm
- tools/modules/EnsEMBL/Web/Component/Tools/Blast/ResultsTable.pm
- tools/modules/EnsEMBL/Web/Component/Tools/DataSlicer/Results.pm
- tools/modules/EnsEMBL/Web/Component/Tools/IDMapper/Results.pm
- tools/modules/EnsEMBL/Web/Component/Tools/InputForm.pm
- tools/modules/EnsEMBL/Web/Component/Tools/LD/Results.pm
- tools/modules/EnsEMBL/Web/Component/Tools/NewJobButton.pm
- tools/modules/EnsEMBL/Web/Component/Tools/VEP/Results.pm
- tools/modules/EnsEMBL/Web/Component/Tools/VcftoPed/Results.pm
- tools/modules/EnsEMBL/Web/Configuration/Tools.pm
Related Ticket:
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5053
Description:
Added new job button to the following tools result page:
1. Blast - Top & bottom
http://ves-hx2-76.ebi.ac.uk:42229/Homo_sapiens/Tools/Blast/Results?db=core;expand_form=true;tl=cRCulE5JJEN87Ysh-877
2. VEP - Top & bottom
http://ves-hx2-76.ebi.ac.uk:42229/Homo_sapiens/Tools/VEP/Results?db=core;expand_form=true;tl=6VBkpE2WUATICMqN-733
3. LD - Top - Link not available
4. IDM - Top & bottom
http://ves-hx2-76.ebi.ac.uk:42229/Homo_sapiens/Tools/IDMapper/Results?db=core;tl=Di3pUFNr5WUf6IAb-640
5. VCF - Top & bottom
http://ves-hx2-76.ebi.ac.uk:42229/Mus_musculus/Tools/VcftoPed/Results?db=core;expand_form=true;tl=IoqoESIZ48RWtGer-70
6. AF - Top - Link not available
> Add new job button on tools result page

- docs/htdocs/info/docs/tools/vep/script/vep_custom.html
sandbox: http://ves-hx2-76.ebi.ac.uk:6080/info/docs/tools/vep/script/vep_custom.html
> remove default format for custom flag 

- tools/modules/EnsEMBL/Web/Component/Tools/AlleleFrequency/Results.pm
- tools/modules/EnsEMBL/Web/Component/Tools/DataSlicer/Results.pm
**Description:**
This PR is to fix a bug with Tools-> Data Slicer -> Results page, introduced in the following PR:
https://github.com/Ensembl/public-plugins/pull/240
**Views affected:**
http://ves-hx2-76.ebi.ac.uk:42228/Homo_sapiens/Tools/DataSlicer/Results?tl=sotkTt3lgIfNX8sw-994
> Fix tools data slicer results page

- ensembl/conf/json/bos_taurus_vcf.json
- ensembl/conf/json/canis_familiaris_vcf.json
- ensembl/conf/json/capra_hircus_vcf.json
- ensembl/conf/json/chlorocebus_sabaeus_vcf.json
- ensembl/conf/json/danio_rerio_vcf.json
- ensembl/conf/json/equus_caballus_vcf.json
- ensembl/conf/json/felis_catus_vcf.json
- ensembl/conf/json/gallus_gallus_vcf.json
- ensembl/conf/json/homo_sapiens_vcf.json
- ensembl/conf/json/macaca_mulatta_vcf.json
- ensembl/conf/json/meleagris_gallopavo_vcf.json
- ensembl/conf/json/mus_musculus_vcf.json
- ensembl/conf/json/nomascus_leucogenys_vcf.json
- ensembl/conf/json/ovis_aries_vcf.json
- ensembl/conf/json/pan_troglodytes_vcf.json
- ensembl/conf/json/pongo_abelii_vcf.json
- ensembl/conf/json/rattus_norvegicus_vcf.json
- ensembl/conf/json/sus_scrofa_vcf.json
- ensembl/conf/json/taeniopygia_guttata_vcf.json
- ensembl/conf/json/tetraodon_nigroviridis_vcf.json
Update to release/99 GERP file names.
> update gerp versions

- ensembl/conf/json/homo_sapiens_vcf.json
Read ESP allele, genotype and frequency data from VCF for GRCh38.
> get ESP data from VCF

- docs/htdocs/info/docs/tools/vep/script/vep_other.html
> Fix URLs in VEP help page

- docs/htdocs/info/docs/api/index.html
Added link to new general instructions page. Removed link to out-of-date video course.
> improved tutorials

- ensembl/htdocs/info/genome/funcgen/peak_calling_report.html
- ensembl/htdocs/info/genome/funcgen/read_file_report.html
- ensembl/htdocs/info/genome/funcgen/regulatory_build_stats.html
- ensembl/htdocs/info/genome/funcgen/segmentation.html
Enabled the pagination for the Regulatory Build Statistics tables
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5391
Sandbox URL:
http://ves-hx2-76.ebi.ac.uk:42229/info/genome/funcgen/peak_calling_report.html
> Peak calling report table pagination

- ga/htdocs/components/95_ga_configs.js
This PR is to make a small change suggested after merging the following PR:
https://github.com/Ensembl/public-plugins/pull/289
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5120
> Add tracking to VEP tool run buttons - v2

- solr/conf/SiteDefs.pm
- solr/htdocs/solr/template_data.js
- solr/src/obj/template_data.coffee
- solr/src/templates/fix_minor_types.coffee
- solr/src/templates/google_templates.coffee
- solr/src/templates/pedestrian_templates.coffee
- solr/src/templates/rhs_templates.coffee
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5337
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5432
Description:
Updated the solr search interface to show different sidebar title texts for strains and breeds.
Sandbox URLs:
**Pig** - http://ves-hx2-76.ebi.ac.uk:42228/Sus_scrofa/Search/Results?q=pig;site=ensembl_all;page=1;facet_species=Pig
**Mouse** - http://ves-hx2-76.ebi.ac.uk:42228/Sus_scrofa/Search/Results?q=pig;site=ensembl_all;page=1;facet_species=Mouse
**Dog** - http://ves-hx2-76.ebi.ac.uk:42228/Sus_scrofa/Search/Results?q=pig;site=ensembl_all;page=1;facet_species=Dog
**Cow** - http://ves-hx2-76.ebi.ac.uk:42228/Sus_scrofa/Search/Results?q=pig;site=ensembl_all;page=1;facet_species=Cow
> Use strain type to identify strains and breeds

- ensembl/conf/json/bos_taurus_vcf.json
- ensembl/conf/json/canis_familiaris_vcf.json
- ensembl/conf/json/capra_hircus_vcf.json
- ensembl/conf/json/chlorocebus_sabaeus_vcf.json
- ensembl/conf/json/danio_rerio_vcf.json
- ensembl/conf/json/equus_caballus_vcf.json
- ensembl/conf/json/felis_catus_vcf.json
- ensembl/conf/json/gallus_gallus_vcf.json
- ensembl/conf/json/macaca_mulatta_vcf.json
- ensembl/conf/json/meleagris_gallopavo_vcf.json
- ensembl/conf/json/mus_musculus_vcf.json
- ensembl/conf/json/nomascus_leucogenys_vcf.json
- ensembl/conf/json/ovis_aries_vcf.json
- ensembl/conf/json/pan_troglodytes_vcf.json
- ensembl/conf/json/pongo_abelii_vcf.json
- ensembl/conf/json/rattus_norvegicus_vcf.json
- ensembl/conf/json/salmo_salar_vcf.json
- ensembl/conf/json/sus_scrofa_vcf.json
- ensembl/conf/json/taeniopygia_guttata_vcf.json
- ensembl/conf/json/tetraodon_nigroviridis_vcf.json
Human is updated in a separate PR
> update gerp file names for release 100

- solr/htdocs/components/71_solr_search.css
- solr/htdocs/solr/search_templates.css
Description:
This PR is to fix the issue with the overlapping elements on the search page when an announcement banner is displayed.
Live URL:
http://grch37.ensembl.org/Multi/Search/Results?q=BRCA2;site=ensembl_all
Sandbox URL:
http://ves-hx2-76.ebi.ac.uk:42228/Multi/Search/Results?q=BRCA2;page=1
> Fix banner overlap issue on the search page

- ensembl/htdocs/info/genome/compara/homology_method.html
- ensembl/htdocs/info/genome/compara/ncRNA_methods.html
- ensembl/htdocs/info/genome/compara/super_trees.html
Jira links: [ENSCOMPARASW-3459](https://www.ebi.ac.uk/panda/jira/browse/ENSCOMPARASW-3459), [ENSWEB-5294](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5294) and [ENSWEB-5414](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5414)
Here is a document that explains super-trees, how we infer orthologues / paralogues between them, and why. It can be linked from the Gene Tree view, when the gene to be highlighted is from a different Gene Tree
> Documentation for super-trees

- ensembl/htdocs/info/genome/compara/species_trees.html
Slightly more detailed description written by @carlacummins , following a user request handled by @michalszpak
> Species-tree doc update

- ensembl/conf/json/homo_sapiens_vcf.json
> update gnomad r3.0 path

- ensembl/htdocs/info/genome/compara/epo_anchor_species.inc
- ensembl/htdocs/info/genome/compara/epo_anchors_info.html
- ensembl/htdocs/info/genome/compara/family.html
- ensembl/htdocs/info/genome/compara/multiple_genome_alignments.html
Following a bug reported by @khowe on Slack
> Updated documentation for the EPO anchors

- tools_hive/conf/vep_plugins_hive_config.txt
Update to latest ancestral allele file
> update ancestral allele fasta file

- solr/htdocs/components/11_selbox.js
Related JIRA:
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5752?jql=project%20%3D%20ENSWEB%20AND%20reporter%20in%20(currentUser())
> Handle missing GA plugin

- docs/htdocs/info/docs/api/core/core_schema.html
Schema diagram update - apologies for these being a bit late.
> updated core schema diagrams for release/101

- tools/conf/vep_plugins_web_config.txt
- tools_hive/conf/vep_plugins_hive_config.txt
Add SpliceAI and DisGeNET plugins to release/102
> Add SpliceAI and DisGeNET plugins to Web VEP

- docs/htdocs/info/docs/tools/vep/script/vep_other.html
> update ncbi bam file location

- ensembl/conf/json/homo_sapiens_vcf.json
Update to latest CADD file version for release/102
> update cadd version

- tools_hive/conf/vep_plugins_hive_config.txt
Update to latest CADD files for release/102.
> update cadd file version

- docs/htdocs/info/docs/api/core/core_schema.html
Version updated to 102 for core schema documentation.
> 102 core schema update

- covid19/conf/SiteDefs.pm
- rapid/conf/SiteDefs.pm
Jira ticket:
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5827
> Update covid and RR sitedefs to create a restrictive robot.txt file.

- docs/htdocs/info/docs/tools/vep/script/vep_download.html
This PR updates the SpliceAI description that was made in #380
> Update variation docs 102 - SpliceAI

- docs/htdocs/info/docs/tools/vep/script/vep_options.html
`--fields` needs updating, user highlighted issue
before:
https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html
after:
http://ves-hx2-76.ebi.ac.uk:6080/info/docs/tools/vep/script/vep_options.html
> Fix VEP documentation for e102

- tools/modules/EnsEMBL/Web/Component/Tools/TicketDetails.pm
Description:
Updated the error message that gets displayed to the user when the tool fails due to FTP timeouts.
Sandbox URL:
http://ves-hx2-75.ebi.ac.uk:42229/Homo_sapiens/Tools/VcftoPed/View?db=core;tl=FRBo3lO00l4Gy2Ya-6483438
Related JIRA:
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5411
> VCFToPED - Display different error message for FTP timeouts

- tools/modules/EnsEMBL/Web/Component/Tools/TicketDetails.pm
Description:
- This PR is just to tweak the error message that was added in the related PR
Related PR:
https://github.com/Ensembl/public-plugins/pull/398
Sandbox URL:
http://ves-hx2-75.ebi.ac.uk:42229/Homo_sapiens/Tools/VcftoPed/View?db=core;tl=FRBo3lO00l4Gy2Ya-6483438
Related JIRA:
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5411
> Tools FTP timeout error message update

- solr/htdocs/solr/search_templates.css
- solr/htdocs/solr/template_data.js
- solr/src/obj/template_data.coffee
- solr/src/templates/page_templates.coffee
- solr/src/templates/page_templates.css
Description
- Changed the position of the sidebar from fixed to absolute and removed the onScroll handler
Related JIRA:
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5593
Sandbox URL: (Minimise the screen size to test)
http://ves-hx2-75.ebi.ac.uk:42228/Multi/Search/Results?q=BRCA2;site=ensembl_all;page=2;perpage=10
> Change sidebar position to absolute

- tools/modules/EnsEMBL/Web/Component/Tools/VEP/Results.pm
live:
https://www.ensembl.org/Rattus_norvegicus/Tools/VEP/Results?tl=KEnvHBPiMVoy30yW-6780946
fix:
http://ves-hx2-76.ebi.ac.uk:7040/Rattus_norvegicus/Tools/VEP/Results?tl=RKI1SZPUFJnVCojN-397 
> fix regex to work only for variation (rs ids)

- ensembl/conf/json/homo_sapiens_vcf.json
For ENSINT-520 and ENSVAR-3702
> Add configuration for GEM-J frequency

- tools/modules/EnsEMBL/Web/Component/Tools/VEP/InputForm.pm
Fix https://github.com/Ensembl/public-plugins/pull/404 
Sandbox: http://ves-hx2-76.ebi.ac.uk:7040/Homo_sapiens/Tools/VEP?tl=hix2ELsDmBobb5II-392
> Fix variant synonyms in web vep

- tools/htdocs/components/20_VEPForm.js
Related JIRA:
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6151
Description:
- This PR fixes the issue with VEP file url validation issue mentioned in the related ticket 
TODO: Need to cherry-pick the changes onto `postreleasefix/103`
Sandbox URL:
http://ves-hx2-75.ebi.ac.uk:42229/Tools/VEP
> Fix VEP file url input

- ensembl/htdocs/info/genome/funcgen/peak_calling_report.html
Update to paginate peak calling statistics
> update to paginate peak_calling_report

- ensembl/htdocs/info/genome/funcgen/peak_calling_report.html
Hopefully this will fix the problem with the pagination in the table.
> fix table pagination

- tools_hive/conf/vep_plugins_hive_config.txt
Update the file name for release/104
> Update Mastermind file name

- ensembl/htdocs/info/genome/variation/species/species_data_types.html
Private db has a new track - Mastermind.
Update docs for release/104
Sandbox: [ves-hx2-76.ebi.ac.uk:7040/info/genome/variation/species/species_data_types.html](ves-hx2-76.ebi.ac.uk:7040/info/genome/variation/species/species_data_types.html)
> Update Variation private database docs

- docs/htdocs/info/docs/tools/vep/index.html
- ensembl/htdocs/info/genome/variation/prediction/predicted_data.html
sandbox: http://ves-hx2-76.ebi.ac.uk:6080/info/genome/variation/prediction/predicted_data.html
> variation docs : add info on default distance

- tools_hive/modules/EnsEMBL/Web/RunnableDB/VR.pm
Input failing: `NM_007294.3:c.2130_2131delinsA`
Sandbox: http://ves-hx2-76.ebi.ac.uk:7040/Homo_sapiens/Tools/VR/Results?tl=vpxcDxvczKgAWth4-875
> Variant Recoder - fix HGVS genomic error

- docs/htdocs/info/docs/api/core/core_schema.html
Core schema diagram update for release 104
> Update Core Schema Diagram for Release 104

- docs/htdocs/info/docs/tools/vep/vep_formats.html
For ENSVAR-4009 and linked to https://github.com/Ensembl/ensembl-vep/issues/938
Sandbox to test: http://ves-hx2-76.ebi.ac.uk:5050/info/docs/tools/vep/vep_formats.html#json
> Update VEP JSON output

- tools/conf/SiteDefs.pm
- tools/modules/EnsEMBL/Web/Component/Tools/DataSlicer/InputForm.pm
- tools/modules/EnsEMBL/Web/Component/Tools/ThousandGenomeInputForm.pm
File path and name updates to resolve 1000G issue. 
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6221
http://ves-hx2-75.ebi.ac.uk:8790/Homo_sapiens/Tools/VcftoPed/Edit?db=core;tl=512Vrp1HVZcLfseP-1633
> Update ftp to http in 1000g file path.

- widgets/htdocs/widgets/95_SpeciesTree.js
- Decided to show reference species
- Fixed bug on filtering using menus
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6093
http://ves-hx-78.ebi.ac.uk:9000/info/about/speciestree.html
> [ENSWEB-6093] missing reference species and other bug fixes

- docs/htdocs/info/docs/tools/vep/script/vep_tutorial.html
- docs/htdocs/info/docs/tools/vep/vep_formats.html
> Update documentation - Existing_variation column

- ensembl/htdocs/info/genome/variation/species/species_data_types.html
> Update mastermind documentation

- ensembl/conf/json/homo_sapiens_vcf.json
For e105
See related PR: https://github.com/Ensembl/ensembl-variation/pull/749
> Update config for NCBI ALFA release 2

- tools_hive/conf/vep_plugins_hive_config.txt
> update dbNSFP version

- docs/htdocs/info/docs/tools/vep/online/input.html
- docs/htdocs/info/docs/tools/vep/script/vep_options.html
Update miRNA option info
- https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4351
and add link to DisGeNET license 
@helensch - these are the all updates I was planning
> minor VEP docs updates

- docs/htdocs/info/docs/api/funcgen/funcgen_schema.html
This PR updates the funcgen schema documentation for release 105
https://www.ensembl.org/info/docs/api/funcgen/funcgen_schema.html
> Update funcgen schema documentation for release 105

- ensembl/conf/ini-files/capra_hircus_blackbengal.ini
- ensembl/conf/ini-files/mus_musculus_129s1svimj.ini
- ensembl/conf/ini-files/mus_musculus_aj.ini
- ensembl/conf/ini-files/mus_musculus_akrj.ini
- ensembl/conf/ini-files/mus_musculus_balbcj.ini
- ensembl/conf/ini-files/mus_musculus_c3hhej.ini
- ensembl/conf/ini-files/mus_musculus_c57bl6nj.ini
- ensembl/conf/ini-files/mus_musculus_casteij.ini
- ensembl/conf/ini-files/mus_musculus_cbaj.ini
- ensembl/conf/ini-files/mus_musculus_dba2j.ini
- ensembl/conf/ini-files/mus_musculus_fvbnj.ini
- ensembl/conf/ini-files/mus_musculus_lpj.ini
- ensembl/conf/ini-files/mus_musculus_nodshiltj.ini
- ensembl/conf/ini-files/mus_musculus_nzohlltj.ini
- ensembl/conf/ini-files/mus_musculus_pwkphj.ini
- ensembl/conf/ini-files/mus_musculus_wsbeij.ini
- ensembl/conf/ini-files/ovis_aries.ini
- ensembl/conf/ini-files/sus_scrofa_bamei.ini
- ensembl/conf/ini-files/sus_scrofa_berkshire.ini
- ensembl/conf/ini-files/sus_scrofa_hampshire.ini
- ensembl/conf/ini-files/sus_scrofa_jinhua.ini
- ensembl/conf/ini-files/sus_scrofa_landrace.ini
- ensembl/conf/ini-files/sus_scrofa_largewhite.ini
- ensembl/conf/ini-files/sus_scrofa_meishan.ini
- ensembl/conf/ini-files/sus_scrofa_pietrain.ini
- ensembl/conf/ini-files/sus_scrofa_rongchang.ini
- ensembl/conf/ini-files/sus_scrofa_tibetan.ini
- ensembl/conf/ini-files/sus_scrofa_usmarc.ini
- ensembl/conf/ini-files/sus_scrofa_wuzhishan.ini
- ensembl/modules/EnsEMBL/Web/Component/Gene/ComparaOrthologs.pm
This PR builds on the one in ensembl-webcode, by removing a parameter that is no longer needed. 
https://github.com/Ensembl/ensembl-webcode/pull/852
It should be merged in when the above has been approved and merged.
> Remove IS_STRAIN_OF parameter - ENSWEB-6090

- tools_hive/conf/vep_plugins_hive_config.txt
> Update Mastermind file version 106

- docs/htdocs/info/docs/tools/vep/vep_formats.html
@sarahhunt @jamie-m-a 
Added notes according to benchmarking test for running VEP with variant names - 
https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4540
> Add VEP benchmarking note

- ensembl/conf/json/homo_sapiens_vcf.json
- ensembl/htdocs/info/genome/variation/species/populations.html
> Update gnomad version for 106

- tools_hive/conf/vep_plugins_hive_config.txt
Updates for ancestral allele file for e106
@dglemos please can you review
> Update ancestral allele file

- docs/htdocs/info/docs/tools/vep/script/vep_custom.html
We have an option to add several `--custom` flags in a single vep command. This PR add an command-line example of how it should be.
http://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html
Run new html and see if it works.
> Add a multiple --custom flags example in vep_custom

- tools/conf/vep_plugins_web_config.txt
- tools/modules/EnsEMBL/Web/Component/Tools/VEP/Results.pm
- tools_hive/conf/vep_plugins_hive_config.txt
IntAct is a new VEP plugin that reports variants effect on molecular interaction.
Details on JIRA ticket - https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-3250
> Add IntAct plugin for web VEP

- ensembl/conf/ini-files/homo_sapiens.ini
- genoverse/modules/EnsEMBL/Web/Controller/Genoverse.pm
- genoverse/modules/EnsEMBL/Web/ImageConfig/Genoverse.pm
Related JIRA:
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6439
Related PR:
https://github.com/Ensembl/ensembl-webcode/pull/873
> Add separate tracks for MANE Select & MANE Plus Clinical

- docs/htdocs/info/docs/tools/vep/script/vep_cache.html
- ensembl/htdocs/info/genome/variation/species/species_detailed_counts.html
[ENSVAR-4680](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4680)
Information : Pull request to update the public docs on the ensembl website
> Minor public updates

- tools_hive/conf/vep_plugins_hive_config.txt
The SpliceAI scores were updated for release 107.
> Update SpliceAI file version

- docs/htdocs/info/docs/api/core/core_schema.html
Core schema diagram update for release 107, using `mysql-ens-sta-1-b` as the staging server.
> Update core schema diagram

- tools/modules/EnsEMBL/Web/Ticket.pm
The current code for some error emails can lead to meaningless messages! I've made the code itself a bit more readable (Harpreet did love to use obscure syntax!) and added the following to the autogenerated message:
* The site name (e.g. useast.ensembl.org) should now appear in the subject line, same as for other tools exceptions
* The message body should include the HTTP referer, which will give some clues as to where to look for the problem.
> Improve error messages from tools

- ensembl/htdocs/info/genome/variation/species/species_data_types.html
Tested in sandbox - 
http://wp-np2-11.ebi.ac.uk:6070/info/genome/variation/species/species_data_types.html
> Update sources page

- docs/htdocs/info/docs/tools/vep/online/input.html
- docs/htdocs/info/docs/tools/vep/script/index.html
- docs/htdocs/info/docs/tools/vep/script/vep_cache.html
- docs/htdocs/info/docs/tools/vep/script/vep_download.html
- docs/htdocs/info/docs/tools/vep/script/vep_example.html
- docs/htdocs/info/docs/tools/vep/script/vep_options.html
- docs/htdocs/info/docs/tools/vep/script/vep_other.html
- docs/htdocs/info/docs/tools/vep/vep_faq.html
- docs/htdocs/info/docs/tools/vep/vep_formats.html
We have updated information in cache + vep command lines. This PR is meant to inform users of these release modifications.
1) Check all alterations in .html are working.
Sandbox: http://wp-np2-11.ebi.ac.uk:7080/
> feat: Add new MAF info to html

- docs/htdocs/info/docs/tools/vep/script/vep_cache.html
ReqSeq version previoulsy pointed to an incorrect value. Modified it to point to the right version
> Corrected ReqSeq version in docs

- tools/modules/EnsEMBL/Web/Component/Tools/Postgap/InputForm.pm
Add a retirement warning box in postgap tool page.
Jira:  https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6587
Sandbox : http://wp-np2-1e.ebi.ac.uk:8380/Homo_sapiens/Tools/Postgap
> Add info box to announce postgap retirement.

- ensembl/conf/json/macaca_mulatta_vcf.json
Add to release/108
Details: ENSVAR-4944
Tested on sandbox: http://wp-np2-11.ebi.ac.uk:7040/Macaca_mulatta/Gene/Variation_Gene/Table?db=core;g=ENSMMUG00000020312;r=5:65376507-65505566
> Add macaque eva vcf config

- ensembl/conf/ini-files/macaca_fascicularis.ini
- ensembl/conf/json/macaca_fascicularis_vcf.json
JIRA - [ENSVAR-4967](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4967)
Adding support for remote EVA Crab-eating macaque variants. 
Sandbox - http://wp-np2-11.ebi.ac.uk:6070/Macaca_fascicularis/Location/View?r=8%3A26559737-26641677
> Changes to support crab-eating macaque

- ensembl/conf/json/sus_scrofa_vcf.json
JIRA: [Card](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4678)
Following alterations in https://github.com/Ensembl/ensembl-variation/pull/843. We need also to include pig CADD in sus_scrofa.json.
Alterations must follow established pattern, for example, human [here](https://github.com/diegomscoelho/public-plugins/blob/6335da99877ea1681e3245c91857766bc95a2566/ensembl/conf/json/homo_sapiens_vcf.json#L331-L338).
> feat: Add pig cadd 108

- ensembl/conf/json/parus_major_vcf.json
Sandbox link: http://wp-np2-11.ebi.ac.uk:6070/Parus_major/Info/Index
> Restoring config for parus_major to use the original VCF

- tools_hive/conf/vep_plugins_hive_config.txt
[ENSVAR-4827](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4827): Renamed 107 ancestral allele file as 108
> Update ancestral allele file (108)

- docs/htdocs/info/docs/tools/vep/script/vep_options.html
[Changing the docs](https://github.com/Ensembl/ensembl-vep/pull/1244/files)
> Changes to the vep_docs

- tools_hive/conf/vep_plugins_hive_config.txt
> Update Mastermind version

- tools_hive/conf/vep_plugins_hive_config.txt
Yeast was added to the db file and hence renamed.
> DB file renamed

- docs/htdocs/info/docs/tools/vep/vep_formats.html
test link - http://wp-np2-11.ebi.ac.uk:7070/info/docs/tools/vep/vep_formats.html
> Add more info to vep strand input

- docs/htdocs/info/docs/tools/vep/recoder/index.html
- tools/modules/EnsEMBL/Web/Component/Tools/VR/InputForm.pm
- tools/modules/EnsEMBL/Web/Component/Tools/VR/Results.pm
Add link to HGMD: [ENSVAR-4363](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4363)
MANE select only available for human: [ENSVAR-4364](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4364)
Sandbox: http://wp-np2-11.ebi.ac.uk:7040/Homo_sapiens/Tools/VR
> Update Variant Recoder

- docs/htdocs/info/docs/tools/vep/script/vep_download.html
[ENSVAR-4874](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4874)
- Check the changes in [my sandbox](http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/script/vep_download.html#singularity).
- Check if the Singularity commands make sense.
> Add Singularity instructions and improve Docker info

- docs/htdocs/info/docs/tools/vep/script/vep_cache.html
[ENSVAR-3718](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-3718)
**This can be for e109**
> Update Polyphen_SIFT plugin url

- ensembl/htdocs/info/genome/funcgen/statistics/annotation.html
Release 109 regulatory feature stats update.
- Jira ticket: [ENSREGULATION-1619](https://www.ebi.ac.uk/panda/jira/browse/ENSREGULATION-1619)
- Sandbox: [stats page](http://wp-np2-25.ebi.ac.uk:6020/info/genome/funcgen/statistics/annotation.html)
> update reg. stats for r109

- tools_hive/conf/vep_plugins_hive_config.txt
[ENSVAR-5086](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5086): Renamed 108 ancestral allele file as 109
> Update ancestral allele file (109)

- ensembl/conf/json/bos_taurus_vcf.json
- ensembl/conf/json/canis_lupus_familiaris_vcf.json
- ensembl/conf/json/canis_lupus_familiarisboxer_vcf.json
- ensembl/conf/json/capra_hircus_vcf.json
- ensembl/conf/json/chlorocebus_sabaeus_vcf.json
- ensembl/conf/json/equus_caballus_vcf.json
- ensembl/conf/json/felis_catus_vcf.json
- ensembl/conf/json/homo_sapiens_vcf.json
- ensembl/conf/json/macaca_fascicularis_vcf.json
- ensembl/conf/json/macaca_mulatta_vcf.json
- ensembl/conf/json/microtus_ochrogaster_vcf.json
- ensembl/conf/json/mus_musculus_vcf.json
- ensembl/conf/json/neovison_vison_vcf.json
- ensembl/conf/json/nomascus_leucogenys_vcf.json
- ensembl/conf/json/ovis_aries_rambouillet_vcf.json
- ensembl/conf/json/ovis_aries_vcf.json
- ensembl/conf/json/pan_troglodytes_vcf.json
- ensembl/conf/json/pongo_abelii_vcf.json
- ensembl/conf/json/rattus_norvegicus_vcf.json
- ensembl/conf/json/sus_scrofa_vcf.json
[ENSVAR-5082](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5082)
> Update gerp files in config (e109)

- tools_hive/conf/vep_plugins_hive_config.txt
Update the file name to the latest version.
Release 109
> Update Mastermind file version release 109

- ensembl/htdocs/info/genome/variation/phenotype/phenotype_annotation.html
- ensembl/htdocs/info/genome/variation/phenotype/sources_phenotype_documentation.html
- ensembl/htdocs/info/genome/variation/prediction/classification.html
- ensembl/htdocs/info/genome/variation/prediction/protein_function.html
- ensembl/htdocs/info/genome/variation/prediction/variant_quality.html
- ensembl/htdocs/info/genome/variation/species/populations.html
- ensembl/htdocs/info/genome/variation/species/sets.html
- ensembl/htdocs/info/genome/variation/species/sources_documentation.html
- ensembl/htdocs/info/genome/variation/species/species_data_types.html
- ensembl/htdocs/info/genome/variation/species/species_detailed_counts.html
Changes in variation docs. The changes can be seen in the sandbox - http://wp-np2-11.ebi.ac.uk:7080/
Go to .html files that are different and check if it's OK.
> feat: Public docs update (e109) - Variation

- docs/htdocs/info/docs/tools/vep/script/vep_options.html
- docs/htdocs/info/docs/tools/vep/vep_formats.html
Alteration to inform HGVS_OFFSET value behavior. Regarding issue (https://github.com/Ensembl/ensembl-vep/issues/1328)
Just check new text information.
http://wp-np2-11.ebi.ac.uk:7080/info/docs/tools/vep/vep_formats.html#vcfout
http://wp-np2-11.ebi.ac.uk:7080/info/docs/tools/vep/script/vep_options.html
> feat: New info about HGVS_OFFSET behavior (e109)

- ensembl/htdocs/ssi/whatsnew.html
I have updated the bullet points for the 109 release.
> Updated What's New bullet points for E109

- docs/htdocs/info/docs/tools/vep/script/vep_other.html
- docs/htdocs/info/docs/tools/vep/vep_formats.html
[ENSVAR-5409](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5409)
Merge #https://github.com/Ensembl/ensembl-variation/pull/942 and #https://github.com/Ensembl/ensembl-vep/pull/1336 first
> Update pick documentation

- tools/modules/EnsEMBL/Web/Component/Tools/VEP/Results.pm
Adjusting UTRAnnotator output in web view.
Sandbox overview check.
> feat: Update on results.pm to UTRAnnotator

- ga/htdocs/components/90_ga.js
- ga/htdocs/components/90_hotjar.js
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-1845
To be merged with https://github.com/Ensembl/ebi-plugins/pull/145/
> Add hotjar

- docs/htdocs/info/docs/tools/vep/script/vep_download.html
- docs/htdocs/info/docs/tools/vep/script/vep_options.html
Mention environment variables in VEP and `INSTALL.pl`.
Check changes in my sandbox:
* Running VEP: http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/script/vep_options.html
* INSTALL script: http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/script/vep_download.html
> Document environment variables in VEP (110)

- tools/conf/vep_plugins_web_config.txt
- tools/modules/EnsEMBL/Web/Component/Tools/VEP/Results.pm
- tools_hive/conf/vep_plugins_hive_config.txt
[ENSVAR-2852](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-2852)
Use `rs28775022` to test web VEP with Geno2MP enabled in my sandbox: http://wp-np2-11.ebi.ac.uk:6070/Tools/VEP
> Add Geno2MP plugin to web VEP (110)

- docs/htdocs/info/docs/tools/vep/script/vep_cache.html
- docs/htdocs/info/docs/tools/vep/script/vep_custom.html
- docs/htdocs/info/docs/tools/vep/script/vep_download.html
- docs/htdocs/info/docs/tools/vep/script/vep_example.html
- docs/htdocs/info/docs/tools/vep/script/vep_options.html
We added prefix to custom flags usage (https://github.com/Ensembl/ensembl-vep/pull/1339). Thereby, we need to update our docs to reflect those alterations.
Start sandbox and look:
1. vep_custom.html;
2. vep_cache.html;
3. vep_options.html;
4. vep_example.html;
5. vep_download.html;
> feat: Add documentation to new custom usage

- docs/htdocs/info/docs/tools/vep/script/vep_download.html
* Document usage of all in species option ([ENSVAR-5527](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5527))
* Add anchor links to all documented options for INSTALL ([ENSVAR-5526](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5526))
Test in my sandbox: http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/script/vep_download.html#opt_species
> Improve docs on VEP installation

- ensembl/conf/json/bos_taurus_vcf.json
- ensembl/conf/json/canis_lupus_familiaris_vcf.json
- ensembl/conf/json/canis_lupus_familiarisboxer_vcf.json
- ensembl/conf/json/capra_hircus_vcf.json
- ensembl/conf/json/chlorocebus_sabaeus_vcf.json
- ensembl/conf/json/equus_caballus_vcf.json
- ensembl/conf/json/felis_catus_vcf.json
- ensembl/conf/json/homo_sapiens_vcf.json
- ensembl/conf/json/macaca_fascicularis_vcf.json
- ensembl/conf/json/macaca_mulatta_vcf.json
- ensembl/conf/json/microtus_ochrogaster_vcf.json
- ensembl/conf/json/mus_musculus_vcf.json
- ensembl/conf/json/neovison_vison_vcf.json
- ensembl/conf/json/nomascus_leucogenys_vcf.json
- ensembl/conf/json/oryctolagus_cuniculus_vcf.json
- ensembl/conf/json/ovis_aries_rambouillet_vcf.json
- ensembl/conf/json/ovis_aries_vcf.json
- ensembl/conf/json/pan_troglodytes_vcf.json
- ensembl/conf/json/pongo_abelii_vcf.json
- ensembl/conf/json/rattus_norvegicus_vcf.json
- ensembl/conf/json/sus_scrofa_vcf.json
[ENSVAR-5339](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5339)
> Update paths to GERP conservation scores for Variation data (110)

- ensembl/conf/json/meleagris_gallopavo_vcf.json
- ensembl/conf/json/nomascus_leucogenys_vcf.json
- ensembl/conf/json/pan_troglodytes_vcf.json
Removing VCF config for following species - 
- Chimpanzee
- Gibbon
- Turkey
Database still contains variant and conflicting with VCF config.
> Remove vcf config for some species (e110)

- tools/modules/EnsEMBL/Web/Component/Tools/VEP/Results.pm
- widgets/htdocs/alphafold/dataFetchers.js
See description in https://github.com/Ensembl/ensembl-webcode/pull/966
**Jira ticket:**
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6763
**Related PRs:**
https://github.com/Ensembl/ensembl-webcode/pull/966
> Do not modify Alphafold ids.

- docs/htdocs/info/docs/tools/vep/haplo/index.html
- docs/htdocs/info/docs/tools/vep/online/index.html
- docs/htdocs/info/docs/tools/vep/vep_faq.html
- ensembl/htdocs/info/genome/variation/index.html
[ENSVAR-5518](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5518)
- Update VEP citation and mention web VEP tutorial article:
- http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/online/index.html
- Add information as new questions to VEP FAQ: http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/vep_faq.html
- General questions - **How to cite VEP?**
- Web VEP questions - **Is there a tutorial for web VEP?**
- Format Variation references in panels:
- http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/haplo/index.html#hp_pub
- http://wp-np2-11.ebi.ac.uk:6070/info/genome/variation/index.html#references
> Fix publication references for Variation resources (e110)

- docs/htdocs/info/docs/tools/vep/script/vep_options.html
[ENSVAR-4683](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4683): related with https://github.com/Ensembl/ensembl-vep/pull/1379
Check changes in my [sandbox](http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/script/vep_options.html#opt_skipped_variants_file)
> VEP: document new `--skipped_variants_file` option (110)

- docs/htdocs/info/docs/tools/vep/script/vep_options.html
related to - https://github.com/Ensembl/ensembl-vep/pull/1421
sandbox test url - http://wp-np2-11.ebi.ac.uk:7070/info/docs/tools/vep/script/vep_options.html#opt_hgvsg
> Add new flag description to VEP public doc (e110)

- docs/htdocs/info/docs/tools/vep/script/vep_custom.html
[ENSVAR-5028](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5028): new options to VEP's `--custom` flag will be added in https://github.com/Ensembl/ensembl-vep/pull/1407.
- Describe `--custom` options in a table
- Add new `--custom` options
- Add a new VCF example using some of the new options
Check changes in my sandbox: http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/script/vep_custom.html#custom_options
> Document new options for VEP custom flag (110)

- ga/htdocs/components/90_ga.js
Also exposed getConfig to resolve blast issue
> Updated GA code to try GA4 and fallback to GAU if there is no GA4 code

- ga/htdocs/components/90_ga.js
- ga/htdocs/components/95_ga_configs.js
- tools/htdocs/components/95_ga_config_tools.js
This PR corrects a couple of errors introduced during integrating GA4
Currently deployed to http://wp-np2-1f.ebi.ac.uk:10000/
Currently connected to https://analytics.google.com -> Dev GA4
> GA blast fix

- ensembl/htdocs/info/genome/variation/species/sources_documentation.html
sandbox url - 
http://wp-np2-11.ebi.ac.uk:7070/info/genome/variation/species/sources_documentation.html
> Remove duplicate source for mink and tilapia in source doc (e110)

- ensembl/htdocs/ssi/species/Homo_sapiens_annotation.html
Addresses [ENSWEB-6841](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6841) and part of [ENSWEB-6842](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6842). Change visible in [staging site](http://staging.ensembl.org/Homo_sapiens/Info/Annotation).
> Remove neandertal, add T2T

- tools_hive/conf/vep_plugins_hive_config.txt
> Update dbNSFP file v4.4a (e111)

- docs/htdocs/info/docs/tools/vep/index.html
- docs/htdocs/info/docs/tools/vep/script/vep_cache.html
- docs/htdocs/info/docs/tools/vep/script/vep_custom.html
- docs/htdocs/info/docs/tools/vep/script/vep_example.html
- docs/htdocs/info/docs/tools/vep/script/vep_options.html
- docs/htdocs/info/docs/tools/vep/vep_faq.html
[ENSVAR-5748](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5748)
Test in my sandbox: http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/index.html
> VEP: clearly document that any species/assembly can be run in CLI (e111)

- docs/htdocs/info/docs/tools/vep/script/vep_options.html
New option available for release 111
[ENSVAR-4523](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4523)
Sandbox: http://wp-np2-11.ebi.ac.uk:7040/info/docs/tools/vep/script/vep_options.html#output
> Document new VEP option --individual_zyg (e111)

- docs/htdocs/info/docs/tools/vep/script/vep_custom.html
[ENSVAR-5925](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5925)
https://github.com/Ensembl/ensembl-vep/pull/1470
Check changes in my sandbox: http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/script/vep_custom.html
> Document `num_records` and `summary_stats` options in VEP custom annotation

- ensembl/htdocs/components/99_variation_docs.css
- ensembl/htdocs/info/genome/variation/phenotype/phenotype_annotation.html
- ensembl/htdocs/info/genome/variation/phenotype/sources_phenotype_documentation.html
- ensembl/htdocs/info/genome/variation/prediction/classification.html
- ensembl/htdocs/info/genome/variation/species/sets.html
- ensembl/htdocs/info/genome/variation/species/sources_documentation.html
- ensembl/htdocs/info/genome/variation/species/species_data_types.html
- ensembl/htdocs/info/genome/variation/species/species_detailed_counts.html
sandbox: http://wp-np2-11.ebi.ac.uk:7070/info/genome/variation/index.html
For variant classification page you can check - http://wp-np2-11.ebi.ac.uk:6070/info/genome/variation/prediction/classification.html
My sandbox is not working
> Update variation data in public docs (e111)

- ensembl/htdocs/info/genome/variation/prediction/protein_function.html
- ensembl/htdocs/info/genome/variation/species/populations.html
- missing frequency sources for human, mink, and tilapia
- missing `low confidence` SIFT predictions in a table
> Fix variation doc for e111

- docs/htdocs/info/docs/tools/vep/script/vep_download.html
sandbox - http://wp-np2-11.ebi.ac.uk:7070/info/docs/tools/vep/script/vep_download.html#new
> Add new plugins to What's New sections (e111)

- docs/htdocs/info/docs/tools/vep/script/vep_options.html
- docs/htdocs/info/docs/tools/vep/vep_formats.html
[ENSVAR-5540](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5540)
Check my sandbox:
* http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/script/vep_options.html#opt_stats_html
* http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/vep_formats.html#stats
> Document VEP flag: `--stats_html` (112)

- docs/htdocs/info/docs/tools/vep/script/vep_download.html
[ENSVAR-6215](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6215)
Sandbox: http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/script/vep_download.html#new
> Fix wrong categories for VEP plugins in What's New (e111)

- tools_hive/conf/vep_plugins_hive_config.txt
Updating the Mastermind file (e112)
> Update file for Mastermind

- docs/htdocs/info/docs/tools/vep/script/vep_download.html
[ENSVAR-6109](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6109)
> Update mysql DBD version (e112)

- docs/htdocs/info/docs/api/core/core_schema.html
This PR contains the updated core schema HTML file for Release 112.
> [e112] Update core schema HTML

- docs/htdocs/info/docs/tools/vep/script/vep_example.html
- docs/htdocs/info/docs/tools/vep/script/vep_options.html
Ticket: [ENSVAR-6130](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6130)
Added example command: http://wp-np2-25.ebi.ac.uk:6080/info/docs/tools/vep/script/vep_example.html
> Docs for minimal allele (e112)

- docs/htdocs/info/docs/tools/vep/online/input.html
- tools/conf/vep_plugins_web_config.txt
- tools/modules/EnsEMBL/Web/Component/Tools/VEP/Results.pm
- tools_hive/conf/vep_plugins_hive_config.txt
[ENSVAR-6261](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6261)
Based on https://github.com/Ensembl/public-plugins/pull/777
> Add AlphaMissense to web VEP (e112)

- docs/htdocs/info/docs/tools/vep/script/vep_download.html
- docs/htdocs/info/docs/tools/vep/script/vep_options.html
sandbox url - http://wp-np2-11.ebi.ac.uk:7070/info/docs/tools/vep/script/vep_options.html
> Add missing option in the "Incompatible with" column (e112)

- docs/htdocs/info/docs/tools/vep/script/vep_cache.html
- docs/htdocs/info/docs/tools/vep/vep_faq.html
sandbox links - 
FAQ - http://wp-np2-11.ebi.ac.uk:7070/info/docs/tools/vep/vep_faq.html
Annotation source - http://wp-np2-11.ebi.ac.uk:7070/info/docs/tools/vep/script/vep_cache.html#gff
> Improve documentation about un-supported GTF/GFF types (e112)

- ensembl/htdocs/info/genome/variation/prediction/protein_function.html
- tools_hive/conf/vep_plugins_hive_config.txt
[ENSVAR-6245](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6245)
> VEP plugins: Update to dbNSFP 4.7c data (e113)

- ensembl/htdocs/info/genome/variation/species/species_data_types.html
Adding the missing VCF species
> new vcf species (e112)

- docs/htdocs/info/docs/tools/vep/script/vep_download.html
Hi web - so sorry, was just arranging the VEP release when I realised we'd missed a plugin off the list for the what's new section.
Is it possible to add it in? It's a very tiny text change
> Adding missing cli plugin (e112 - if possible!)

- widgets/htdocs/alphafold/components/confidenceMissenseToggle.js
- widgets/htdocs/alphafold/components/ensemblAlphafoldMissense.js
Tiny change to correct missing </div> and .log omission error
> Corrected a div close and .log issue

- docs/htdocs/info/docs/tools/vep/vep_faq.html
[ENSVAR-6224](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6224):
- Avoid generic questions like "Why do I see the following error"
- Add anchor links to every question
- Use `<h3>` heading for the questions
Check in [my sandbox](http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/vep_faq.html#indel-vcf).
> Improve VEP FAQ

- docs/htdocs/info/docs/tools/vep/script/vep_options.html
sandbox url - http://wp-np2-11.ebi.ac.uk:7070/info/docs/tools/vep/script/vep_options.html#opt_mane
> Update docs to note changes in --mane --mane_select flags (e113)

- docs/htdocs/info/docs/tools/vep/script/vep_options.html
- docs/htdocs/info/docs/tools/vep/script/vep_other.html
[ENSVAR-6372](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6372)
> Notes for the exclude predicted

- docs/htdocs/info/docs/tools/vep/script/vep_options.html
[ENSVAR-6330](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6330)
sandbox url - http://wp-np2-11.ebi.ac.uk:7070/info/docs/tools/vep/script/vep_options.html#opt_gene_version
> Update vep options page with new option --gene_version

- docs/htdocs/info/docs/tools/vep/script/vep_cache.html
- ensembl/conf/json/homo_sapiens_vcf.json
[ENSVAR-6286](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6286)
related changes - 
https://github.com/Ensembl/ensembl-variation/pull/1094
sandbox url - http://wp-np2-11.ebi.ac.uk:7070/Homo_sapiens/Variation/Population?db=core;r=1:9557-10557;v=rs1570391741;vdb=variation;vf=54392173
Doc update:
- VEP annotation source , sandbox [url](http://wp-np2-11.ebi.ac.uk:7070/info/docs/tools/vep/script/vep_cache.html)
- Population page - will be updated once the script is run (not part of this PR)
> Add gnomAD v4.1 populations (e113)

- ensembl/htdocs/info/genome/variation/prediction/classification.html
Updating sequence_alteration short variant example, current example points to a multimapped SNP, looked a bit messy.
> New example variant

- tools/htdocs/components/20_VEPForm.js
- tools/modules/EnsEMBL/Web/Component/Tools/VEP/InputForm.pm
- tools/modules/EnsEMBL/Web/Job/VEP.pm
- tools/modules/EnsEMBL/Web/Object/VEP.pm
Sandbox link: http://wp-np2-11.ebi.ac.uk:7070/Homo_sapiens/Tools/VEP/Results?tl=S6m4w5Uhg4HyA4XM-9
Depends on:
https://github.com/Ensembl/ensembl-variation/pull/1107
https://github.com/Ensembl/ensembl-vep/pull/1699
> Add GENCODE primary support for VEP

- docs/htdocs/info/docs/tools/vep/script/vep_options.html
sandbox url: http://wp-np2-11.ebi.ac.uk:7070/info/docs/tools/vep/script/vep_options.html
> VEP doc: add default value for --max_sv_size

- ensembl/htdocs/info/genome/variation/phenotype/phenotype_annotation.html
- ensembl/htdocs/info/genome/variation/phenotype/sources_phenotype_documentation.html
- ensembl/htdocs/info/genome/variation/prediction/classification.html
- ensembl/htdocs/info/genome/variation/species/populations.html
- ensembl/htdocs/info/genome/variation/species/sets.html
- ensembl/htdocs/info/genome/variation/species/sources_documentation.html
- ensembl/htdocs/info/genome/variation/species/species_data_types.html
- ensembl/htdocs/info/genome/variation/species/species_detailed_counts.html
test url -  http://wp-np2-11.ebi.ac.uk:7070/info/docs/api/variation/index.html
> Public docs update (e113) - Variation docs

- ensembl/conf/json/homo_sapiens_vcf.json
Ticket: [ENSVAR-6201](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6201)
> Update cadd version for human

- docs/htdocs/info/docs/api/funcgen/funcgen_schema.html
- docs/htdocs/info/docs/api/funcgen/index.html
- docs/htdocs/info/docs/api/funcgen/regulation_tutorial.html
- ensembl/htdocs/info/genome/microarray_probe_set_mapping.html
Add deprecation notes for the funcgen API and database
Add maintenance mode note for microarray probe mapping
> Add deprecation notes for Regulation for e113

- docs/htdocs/info/docs/api/funcgen/funcgen_schema.html
- docs/htdocs/info/docs/api/funcgen/index.html
- docs/htdocs/info/docs/api/funcgen/regulation_tutorial.html
- ensembl/htdocs/info/genome/microarray_probe_set_mapping.html
Minor clarifications to docs for e113
> Minor updates to Regulation docs for e113

- ensembl/htdocs/info/genome/variation/prediction/protein_function.html
- tools_hive/conf/vep_plugins_hive_config.txt
[ENSVAR-6368](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6368)
> Update dbNSFP data to 4.8c and 4.9c (e114)

- genoverse/modules/EnsEMBL/Web/ImageConfig/Genoverse.pm
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6951
This PR needs to go with https://github.com/Ensembl/ensembl-webcode/pull/1040
Task: Hide Comprehensive transcript track and enable gencode basic. 
This PR updates genoverse tracks.
> turn off gencode comprehensive and enable gencode basic track

- docs/htdocs/info/docs/tools/vep/vep_formats.html
https://github.com/Ensembl/ensembl-vep/issues/1147
sandbox url - http://wp-np2-11.ebi.ac.uk:7070/info/docs/tools/vep/vep_formats.html
> VEP doc: explanation of distance=0 in case of insertion (e114)

- docs/htdocs/info/docs/tools/vep/script/vep_example.html
https://github.com/Ensembl/public-plugins/pull/839
> VEP docs - pangenome protein function link does not work

- docs/htdocs/info/docs/tools/vep/script/vep_cache.html
Ticket: [ENSVAR-6628](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6628)
Sandbox: http://wp-np2-25.ebi.ac.uk:6080/info/docs/tools/vep/script/vep_cache.html#cache
> Update cache docs to remove reference for indexed cache (114)

- ensembl/conf/ini-files/homo_sapiens.ini
Update ini file for human with the new compara "age of base" / AoB file name
> Update AoB in ini files

- docs/htdocs/info/docs/tools/vep/script/vep_download.html
- docs/htdocs/info/docs/tools/vep/script/vep_options.html
- tools/conf/vep_custom_web_config.json
- tools/modules/EnsEMBL/Web/Component/Tools/VEP/InputForm.pm
sandbox url - http://wp-np2-11.ebi.ac.uk:7070/Homo_sapiens/Tools/VEP/Results?tl=qf8p6c5QZIetPVc6-22
> Add NIH AllOfUs frequency config for web VEP

- docs/htdocs/info/docs/tools/vep/index.html
- docs/htdocs/info/docs/tools/vep/script/vep_cache.html
- docs/htdocs/info/docs/tools/vep/script/vep_example.html
- docs/htdocs/info/docs/tools/vep/script/vep_filter.html
- docs/htdocs/info/docs/tools/vep/script/vep_other.html
- docs/htdocs/info/docs/tools/vep/script/vep_plugins.html
- docs/htdocs/info/docs/tools/vep/script/vep_tutorial.html
- docs/htdocs/info/docs/tools/vep/vep_faq.html
- docs/htdocs/info/docs/tools/vep/vep_formats.html
- ensembl/htdocs/info/genome/variation/prediction/predicted_data.html
- ensembl/htdocs/info/genome/variation/prediction/protein_function.html
- ensembl/htdocs/info/genome/variation/species/species_data_types.html
- ensembl/htdocs/info/genome/variation/tools/variant_tools.html
Updates to Ensembl VEP/Variation docs in line with trademark.
Not planning on updating all old new, but some more to come.
> update Ensembl VEP naming (114)

- docs/htdocs/info/docs/tools/vep/script/vep_cache.html
sandbox url - http://wp-np2-11.ebi.ac.uk:7070/info/docs/tools/vep/script/vep_cache.html#limitations
> Add help text for existing variant in cache (114)

- docs/htdocs/info/docs/tools/vep/script/vep_download.html
sandbox url - http://wp-np2-11.ebi.ac.uk:7070/info/docs/tools/vep/script/vep_download.html#requirements
> Update supported perl version (115)

- docs/htdocs/info/docs/tools/vep/script/vep_download.html
sandbox - http://wp-np2-35.ebi.ac.uk:7070/info/docs/tools/vep/script/vep_download.html#new
> Add update MaveDB data information on VEP What's new - 114

- ensembl/htdocs/info/genome/compara/synteny.html
This PR would update Vertebrates synteny docs for e115.
Related ticket(s):
- ENSCOMPARASW-8495
- ENSCOMPARASW-8496
See also:
- [eg-web-common PR 145](https://github.com/EnsemblGenomes/eg-web-common/pull/145)
- [eg-web-plants PR 86](https://github.com/EnsemblGenomes/eg-web-plants/pull/86)
> Update Vertebrates synteny docs for e115

- ensembl/conf/ini-files/homo_sapiens.ini
Updating the homo sapiens ini with the new AoB file for release 115.
> Update for new AoB

- ensembl/htdocs/info/genome/compara/homology_method.html
- ensembl/htdocs/info/genome/compara/ncRNA_methods.html
This PR would update ncRNA-tree documentation, and make an adjustment to protein-tree docs.
> Update ncRNA and protein tree docs

- ensembl/htdocs/info/genome/compara/hmm_lib.html
> Updated the HMM library page.

- docs/htdocs/info/docs/tools/vep/script/vep_example.html
Adding some additional citation links for VEP
> EPMC links

- docs/htdocs/info/docs/tools/vep/script/vep_cache.html
> Cache docs update (e116)

- docs/htdocs/info/docs/tools/vep/script/vep_options.html
> Update --keep_csq option doc for VEP (e116)

- docs/htdocs/info/docs/tools/vep/script/vep_options.html
> --bam VEP option clarification (e116)
